# Generated by Django 4.2.5 on 2023-12-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_alter_tour_id_alter_touristattraction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='touristattraction',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
