# Generated by Django 4.2.5 on 2024-01-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='document',
            field=models.ManyToManyField(blank=True, to='common.document'),
        ),
    ]
