# Generated by Django 4.2.3 on 2023-08-25 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_alter_systemsettingspic_name'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyPersonRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_person_role', to='common.person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_person_role', to='common.roles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyAddressRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_address_role', to='common.places')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.company')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_adress_role', to='common.roles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='address_roles',
            field=models.ManyToManyField(related_name='companies', to='administration.companyaddressrole'),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.legalentity'),
        ),
        migrations.AddField(
            model_name='company',
            name='personnel_roles',
            field=models.ManyToManyField(related_name='companies', to='administration.companypersonrole'),
        ),
    ]
