# Generated by Django 4.2.5 on 2024-01-04 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('administration', '0002_company_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='legal_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.legalentity'),
        ),
    ]
