# Generated by Django 4.2.3 on 2023-08-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_alter_systemsettingspic_name'),
        ('administration', '0002_company_companypersonrole_companyaddressrole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='document',
            field=models.ManyToManyField(blank=True, to='common.document'),
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='Company Name'),
        ),
    ]
