# Generated by Django 4.2.3 on 2023-09-11 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_company_description_company_document_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyaddressrole',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companypersonrole',
            name='company',
        ),
    ]
