# Generated by Django 4.2.3 on 2023-09-11 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_remove_companyaddressrole_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyWebsite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('url', models.URLField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_website', to='administration.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
