# Generated by Django 5.0.1 on 2024-02-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_company_is_deleted_companyaddressrole_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='companyaddressrole',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='companypersonrole',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='companywebsite',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='internalmessage',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
    ]
