# Generated by Django 4.2.5 on 2024-01-04 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('administration', '0005_companyaddressrole_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypersonrole',
            name='job_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_person_role', to='common.jobroles'),
        ),
    ]
