# Generated by Django 4.2.3 on 2023-09-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_companywebsite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companywebsite',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
