# Generated by Django 4.2.3 on 2023-09-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_alter_companywebsite_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companywebsite',
            name='url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
