# Generated by Django 4.2.5 on 2023-09-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_alter_companywebsite_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Company Name'),
        ),
    ]
