# Generated by Django 4.2.5 on 2024-01-04 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_employee_user'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setting_menus', to='administration.company'),
        ),
    ]
