# Generated by Django 4.1.5 on 2023-07-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='places',
            old_name='_statee',
            new_name='_state',
        ),
    ]
