# Generated by Django 4.2.3 on 2023-07-29 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='place_manager', to='common.places'),
        ),
        migrations.AlterField(
            model_name='places',
            name='manager',
            field=models.ForeignKey(db_column='manager', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_place', to='common.person', verbose_name='Manager'),
        ),
    ]
