# Generated by Django 5.0.1 on 2024-01-29 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_user_managers_remove_pictures_image_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='image_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='common.systemsettingspic'),
        ),
    ]
