# Generated by Django 4.2.3 on 2023-07-30 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_person__address_alter_places_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='_address',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='places',
            name='manager',
            field=models.ForeignKey(blank=True, db_column='manager', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_place', to='common.person', verbose_name='Manager'),
        ),
    ]
