# Generated by Django 4.2.3 on 2023-08-17 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_legaltypes_legalentity_classification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='نام دسته بندی')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicRank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='نام رتبه علمی')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('duration_years', models.PositiveIntegerField(verbose_name='مدت زمان (سال)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='نام دانشگاه')),
                ('website', models.URLField(verbose_name='وب\u200cسایت')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.location', verbose_name='موقعیت جغرافیایی')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='classification',
            name='sub_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub Classifications Name'),
        ),
        migrations.CreateModel(
            name='UniversityPlaces',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=80, verbose_name='نام پردیس')),
                ('description', models.TextField()),
                ('places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_places', to='common.places')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university_places', to='common.classification')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_places', to='common.university')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='university',
            name='places',
            field=models.ManyToManyField(related_name='university', through='common.UniversityPlaces', to='common.places'),
        ),
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='نام رشته تحصیلی')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('classification', models.ManyToManyField(related_name='field_of_study', to='common.classification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationalDegree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='نام مدرک')),
                ('abbreviation', models.CharField(max_length=20, verbose_name='مخفف مدرک')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('duration_years', models.PositiveIntegerField(verbose_name='مدت زمان (سال)')),
                ('academic_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.academicrank', verbose_name='رتبه علمی')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.academiccategory', verbose_name='دسته بندی')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('graduation_year', models.PositiveIntegerField(verbose_name='سال فارغ\u200cالتحصیلی')),
                ('gpa', models.FloatField(verbose_name='معدل')),
                ('academic_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.academiccategory', verbose_name='دسته\u200cبندی علمی')),
                ('academic_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.academicrank', verbose_name='رتبه علمی')),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.fieldofstudy', verbose_name='رشته تحصیلی')),
                ('medical_degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.educationaldegree', verbose_name='مدرک')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.person', verbose_name='فرد')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.university', verbose_name='دانشگاه')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='academicrank',
            name='field_of_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_rank', to='common.fieldofstudy', verbose_name='رشته تحصیلی'),
        ),
    ]
