# Generated by Django 4.1.5 on 2023-07-26 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename__statee_places__state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='places',
            old_name='_state',
            new_name='_statee',
        ),
    ]
