# Generated by Django 4.2.3 on 2023-08-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_academiccategory_academicrank_university_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettingsPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(choices=[('administration', 'administration'), ('food', 'food'), ('nursing', 'nursing'), ('shopping', 'shopping'), ('tourism', 'tourism'), ('accommodation', 'accommodation'), ('transportation', 'transportation'), ('treatment', 'treatment'), ('common', 'common'), ('communication', 'communication'), ('financialhub', 'financialhub'), ('django_extensions', 'django_extensions'), ('django.contrib.admin', 'django.contrib.admin'), ('django.contrib.auth', 'django.contrib.auth'), ('django.contrib.contenttypes', 'django.contrib.contenttypes'), ('django.contrib.sessions', 'django.contrib.sessions'), ('django.contrib.messages', 'django.contrib.messages'), ('django.contrib.staticfiles', 'django.contrib.staticfiles')], max_length=40)),
                ('name', models.CharField(choices=[('swiper', 'Swiper'), ('prfpic', 'Profile Picture')], max_length=30)),
                ('max_image_size_width', models.PositiveIntegerField(default=1200, verbose_name='Max Image Size Width')),
                ('max_image_size_height', models.PositiveIntegerField(default=800, verbose_name='Max Image Size Height')),
                ('max_image_file_size', models.PositiveIntegerField(default=2097152, verbose_name='Max Image File Size')),
                ('allowed_image_formats', models.JSONField(default=list, verbose_name='Allowed Image Formats')),
            ],
        ),
        migrations.RenameField(
            model_name='classification',
            old_name='sub_name',
            new_name='sub_class',
        ),
    ]
