# Generated by Django 4.1.5 on 2023-07-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_rename__state_places__statee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='_address',
        ),
        migrations.RemoveField(
            model_name='places',
            name='_city',
        ),
        migrations.RemoveField(
            model_name='places',
            name='_country',
        ),
        migrations.RemoveField(
            model_name='places',
            name='_manager',
        ),
        migrations.RemoveField(
            model_name='places',
            name='_phoneNumber',
        ),
        migrations.RemoveField(
            model_name='places',
            name='_postalcode',
        ),
        migrations.RemoveField(
            model_name='places',
            name='_statee',
        ),
        migrations.RemoveField(
            model_name='places',
            name='_usage',
        ),
    ]
