# Generated by Django 4.1.5 on 2023-07-22 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=64, null=True)),
                ('city', models.CharField(max_length=64, null=True)),
                ('address', models.CharField(max_length=1024, null=True)),
                ('usage', models.CharField(max_length=1024, null=True)),
                ('createddtm', models.DateTimeField(auto_now_add=True)),
                ('updatedtm', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=64, null=True)),
                ('lastname', models.CharField(max_length=80, null=True)),
                ('birthdate', models.DateField(null=True)),
                ('national_code', models.CharField(max_length=10, null=True)),
                ('pasport_number', models.CharField(max_length=8, null=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('mobile_phone', models.CharField(max_length=15, null=True)),
                ('createddtm', models.DateTimeField(auto_now_add=True)),
                ('updatedtm', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField()),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.places')),
            ],
        ),
    ]
