# Generated by Django 4.2.5 on 2024-01-07 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_systemsettingspic_company'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
