# Generated by Django 4.1.5 on 2023-07-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_places_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='person',
            name='pasport_number',
        ),
        migrations.AddField(
            model_name='person',
            name='passport_number',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='createddtm',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='updatedtm',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
