# Generated by Django 5.0.1 on 2024-01-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettingspic',
            name='max_image_file_size_mb',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Enter the maximum image file size in megabytes (MB).', max_digits=5, verbose_name='Max Image File Size (MB)'),
        ),
    ]
