# Generated by Django 4.1.5 on 2023-07-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_places__address_remove_places__city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='_address',
            field=models.CharField(db_column='address', max_length=1966, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='places',
            name='_city',
            field=models.CharField(db_column='city', max_length=686, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='places',
            name='_country',
            field=models.CharField(db_column='country', max_length=686, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='places',
            name='_statee',
            field=models.CharField(db_column='state', max_length=686, null=True, verbose_name='State'),
        ),
    ]
