# Generated by Django 4.1.5 on 2023-07-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_places__address_places__city_places__country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='_address',
        ),
        migrations.RemoveField(
            model_name='places',
            name='_city',
        ),
        migrations.RemoveField(
            model_name='places',
            name='_statee',
        ),
    ]
