# Generated by Django 4.1.5 on 2023-07-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_person_firstname_remove_person_pasport_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='_firstname',
            field=models.CharField(db_column='firstname', max_length=30, null=True),
        ),
    ]
