# Generated by Django 5.0.1 on 2024-02-03 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_systemsettingspic_max_image_file_size_mb'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='systemsettingspic',
            unique_together={('app', 'name', 'deleted_at')},
        ),
    ]
