# Generated by Django 4.1.5 on 2023-07-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_person__firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='_firstname',
            field=models.CharField(db_column='firstname', max_length=10000, null=True),
        ),
    ]
