# Generated by Django 4.2.3 on 2023-08-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_systemsettingspic_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettingspic',
            name='allowed_image_formats',
            field=models.JSONField(default=['jpg', 'png', 'jpeg'], verbose_name='Allowed Image Formats'),
        ),
    ]
