# Generated by Django 5.0.1 on 2024-02-06 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_pictures_name_alter_pictures_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pictures',
            unique_together={('user', 'name', 'deleted_at')},
        ),
    ]
