# Generated by Django 4.1.5 on 2023-07-26 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_places__statee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='_statee',
        ),
        migrations.AddField(
            model_name='places',
            name='_address',
            field=models.CharField(db_column='address', max_length=1966, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='places',
            name='_city',
            field=models.CharField(db_column='city', max_length=686, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='places',
            name='_manager',
            field=models.ForeignKey(db_column='manager', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Places', to='common.person', verbose_name='Manager'),
        ),
        migrations.AddField(
            model_name='places',
            name='_phoneNumber',
            field=models.CharField(db_column='phone_number', max_length=606, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='places',
            name='_postalcode',
            field=models.CharField(db_column='postalcode', max_length=606, null=True, verbose_name='Postalcode'),
        ),
        migrations.AddField(
            model_name='places',
            name='_usage',
            field=models.TextField(db_column='usage', null=True, verbose_name='Usage'),
        ),
    ]
