# Generated by Django 4.2.3 on 2023-08-22 16:44

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_systemsettingspic_allowed_image_formats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettingspic',
            name='allowed_image_formats',
            field=models.JSONField(default=common.models.default_allowed_image_formats, verbose_name='Allowed Image Formats'),
        ),
    ]
