# Generated by Django 4.1.5 on 2023-07-23 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_rename__firstname_person_firstname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='firstname',
            new_name='_firstname',
        ),
    ]
