# Generated by Django 4.2.3 on 2023-08-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_systemsettingspic_allowed_image_formats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettingspic',
            name='max_image_file_size',
        ),
        migrations.AddField(
            model_name='systemsettingspic',
            name='max_image_file_size_mb',
            field=models.PositiveIntegerField(default=2, help_text='Enter the maximum image file size in megabytes (MB).', verbose_name='Max Image File Size (MB)'),
        ),
    ]
