# Generated by Django 4.1.5 on 2023-07-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_remove_places__manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='_statee',
            field=models.CharField(db_column='state', max_length=686, null=True, verbose_name='State'),
        ),
    ]
