# Generated by Django 4.1.5 on 2023-07-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_rename_firstname_person__firstname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
        migrations.RemoveField(
            model_name='person',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='person',
            name='mobile_phone',
        ),
        migrations.RemoveField(
            model_name='person',
            name='national_code',
        ),
        migrations.RemoveField(
            model_name='person',
            name='passport_number',
        ),
        migrations.AddField(
            model_name='person',
            name='_address',
            field=models.CharField(blank=True, db_column='address', max_length=1936, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='_lastname',
            field=models.CharField(db_column='lastname', max_length=1296, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='_mobile_phone',
            field=models.CharField(db_column='mobile_phone', max_length=656, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='_national_code',
            field=models.CharField(db_column='national_code', max_length=496, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='_passport_number',
            field=models.CharField(db_column='passport_number', max_length=496, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='_firstname',
            field=models.CharField(db_column='firstname', max_length=976, null=True),
        ),
    ]
