# Generated by Django 4.1.5 on 2023-07-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_remove_person_address_remove_person_lastname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='person',
            name='_birthdate',
            field=models.CharField(db_column='birthdate', max_length=624, null=True),
        ),
    ]
