# Generated by Django 5.0.1 on 2024-02-06 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_academiccategory_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pictures',
            unique_together=set(),
        ),
    ]
