# Generated by Django 4.1.5 on 2023-07-26 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_remove_places__statee'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='_manager',
            field=models.ForeignKey(db_column='manager', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Places', to='common.person', verbose_name='Manager'),
        ),
    ]
