# Generated by Django 4.1.5 on 2023-07-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_remove_person_birthdate_person__birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='sex',
        ),
        migrations.AddField(
            model_name='person',
            name='_sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
