# Generated by Django 4.2.3 on 2023-08-22 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_pictures_image_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='image_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='common.systemsettingspic'),
        ),
    ]
