# Generated by Django 4.1.5 on 2023-07-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_places__manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='places',
            old_name='_manager',
            new_name='manager',
        ),
    ]
