# Generated by Django 4.1.5 on 2023-07-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_remove_person_sex_person__sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='_sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], db_column='sex', max_length=496, null=True),
        ),
    ]
