# Generated by Django 4.2.3 on 2023-08-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_pictures_image_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
