# Generated by Django 4.2.3 on 2023-08-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_pictures_image_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='image_width', null=True),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='image_width', null=True),
        ),
    ]
