# Generated by Django 4.2.3 on 2023-08-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_alter_pictures_image_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pictures',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
