# Generated by Django 4.1.5 on 2023-07-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_places__statee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitemanagementslog',
            old_name='_person',
            new_name='person',
        ),
    ]
