# Generated by Django 4.1.5 on 2023-07-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_alter_person__address_alter_person__birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='_sex',
            field=models.TextField(choices=[('Male', 'Male'), ('Female', 'Female')], db_column='sex', null=True),
        ),
    ]
