# Generated by Django 4.1.5 on 2023-07-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_rename__person_sitemanagementslog_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createddtm', models.DateTimeField(auto_now_add=True)),
                ('updatedtm', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('persian', models.TextField(blank=True, null=True)),
                ('english', models.TextField(blank=True, null=True)),
                ('arabic', models.TextField(blank=True, null=True)),
                ('russian', models.TextField(blank=True, null=True)),
                ('chineseTraditional', models.TextField(blank=True, null=True)),
                ('spanish', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
