# Generated by Django 4.2.3 on 2023-08-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_pictures_description_pictures_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
