# Generated by Django 4.1.5 on 2023-07-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_translate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='_birthdate',
            field=models.CharField(db_column='birthdate', max_length=526, null=True, verbose_name='Birthdate'),
        ),
    ]
