# Generated by Django 4.2.3 on 2023-08-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_alter_pictures_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettingspic',
            name='name',
            field=models.CharField(choices=[('swiper', 'Swiper'), ('prfpic', 'Profile Picture'), ('cflag', 'Contry Flag')], max_length=30),
        ),
    ]
