# Generated by Django 4.1.5 on 2023-07-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_alter_person__sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='_sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], db_column='sex', max_length=496, null=True),
        ),
    ]
