# Generated by Django 4.2.3 on 2023-08-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_alter_systemsettingspic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='classification',
        ),
    ]
