# Generated by Django 4.2.3 on 2023-08-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_remove_document_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='classification',
            field=models.ManyToManyField(related_name='common_document', to='common.classification'),
        ),
    ]
