# Generated by Django 4.2.3 on 2023-08-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_remove_document_classification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.DeleteModel(
            name='GroupsUser',
        ),
    ]
