# Generated by Django 4.2.3 on 2023-09-04 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_translate_french_translate_german_translate_italian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldofstudy',
            name='classification',
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_of_study', to='common.classification'),
        ),
    ]
