# Generated by Django 4.2.3 on 2023-09-05 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_remove_fieldofstudy_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldofstudy',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_of_study', to='common.classification', verbose_name='نوع رشته تحصیلی'),
        ),
    ]
