# Generated by Django 4.2.3 on 2023-09-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_alter_fieldofstudy_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrank',
            name='duration_years',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت زمان (سال)'),
        ),
    ]
