# Generated by Django 4.2.3 on 2023-09-05 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_alter_academicrank_duration_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicrank',
            name='duration_years',
        ),
        migrations.RemoveField(
            model_name='academicrank',
            name='field_of_study',
        ),
        migrations.RemoveField(
            model_name='educationaldegree',
            name='academic_rank',
        ),
        migrations.RemoveField(
            model_name='educationaldegree',
            name='category',
        ),
    ]
