# Generated by Django 4.2.3 on 2023-09-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_remove_academicrank_duration_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationaldegree',
            name='abbreviation',
            field=models.CharField(max_length=100, verbose_name='مخفف مدرک'),
        ),
    ]
