# Generated by Django 4.2.3 on 2023-09-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_settingmenus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingmenus',
            name='application',
            field=models.CharField(choices=[('administration', 'administration'), ('food', 'food'), ('nursing', 'nursing'), ('shopping', 'shopping'), ('tourism', 'tourism'), ('accommodation', 'accommodation'), ('transportation', 'transportation'), ('treatment', 'treatment'), ('common', 'common'), ('communication', 'communication'), ('financialhub', 'financialhub'), ('django_extensions', 'django_extensions'), ('admin', 'django.contrib.admin'), ('auth', 'django.contrib.auth'), ('contenttypes', 'django.contrib.contenttypes'), ('sessions', 'django.contrib.sessions'), ('messages', 'django.contrib.messages'), ('staticfiles', 'django.contrib.staticfiles')], max_length=255),
        ),
    ]
