# Generated by Django 4.2.3 on 2023-09-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_alter_settingmenus_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingmenus',
            name='application',
            field=models.CharField(choices=[('administration', 'administration'), ('food', 'food'), ('nursing', 'nursing'), ('shopping', 'shopping'), ('tourism', 'tourism'), ('accommodation', 'accommodation'), ('transportation', 'transportation'), ('treatment', 'treatment'), ('common', 'common'), ('communication', 'communication'), ('financialhub', 'financialhub')], max_length=255),
        ),
    ]
