# Generated by Django 4.2.3 on 2023-09-07 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_alter_settingmenus_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingmenus',
            name='page_name',
            field=models.CharField(choices=[], max_length=255, null=True),
        ),
    ]
