# Generated by Django 4.2.3 on 2023-09-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_settingmenus_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingmenus',
            name='page_name',
            field=models.CharField(choices=[(2, 2)], max_length=255, null=True),
        ),
    ]
