# Generated by Django 4.2.3 on 2023-09-07 00:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0033_alter_settingmenus_page_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingmenus',
            name='index',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(32766)]),
        ),
        migrations.AddField(
            model_name='settingmenus',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='settingmenus',
            name='page_name',
            field=models.CharField(max_length=255),
        ),
    ]
