# Generated by Django 4.2.3 on 2023-09-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_settingmenus_index_settingmenus_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingmenus',
            name='page_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
