# Generated by Django 4.2.3 on 2023-09-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0035_alter_settingmenus_page_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingmenus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='settingmenus',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='settingmenus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='settingmenus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
