# Generated by Django 4.2.3 on 2023-09-07 01:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0036_settingmenus_created_at_settingmenus_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingmenus',
            name='level',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
    ]
