# Generated by Django 4.2.3 on 2023-09-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0038_alter_settingmenus_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingmenus',
            name='level',
            field=models.CharField(max_length=70),
        ),
    ]
