# Generated by Django 4.2.3 on 2023-09-07 08:08

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0039_alter_settingmenus_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingmenus',
            options={'ordering': ['application', 'page_name', 'index', 'level']},
        ),
        migrations.AlterField(
            model_name='settingmenus',
            name='level',
            field=models.CharField(max_length=70, validators=[common.models.validate_level]),
        ),
    ]
