# Generated by Django 4.2.3 on 2023-09-07 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_company_description_company_document_company_name'),
        ('common', '0040_alter_settingmenus_options_alter_settingmenus_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingmenus',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setting_menus', to='administration.company'),
        ),
    ]
