# Generated by Django 4.2.3 on 2023-09-08 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_company_description_company_document_company_name'),
        ('common', '0043_user_mobile_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingmenus',
            options={'ordering': ['cat', 'index', 'level']},
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('application', models.CharField(choices=[('administration', 'administration'), ('food', 'food'), ('nursing', 'nursing'), ('shopping', 'shopping'), ('tourism', 'tourism'), ('accommodation', 'accommodation'), ('transportation', 'transportation'), ('treatment', 'treatment'), ('common', 'common'), ('communication', 'communication'), ('financialhub', 'financialhub')], max_length=255)),
                ('page', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=30, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setting_menus', to='administration.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='settingmenus',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='settingmenus',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='common.setting'),
        ),
        migrations.AlterUniqueTogether(
            name='settingmenus',
            unique_together={('cat', 'index', 'level')},
        ),
        migrations.RemoveField(
            model_name='settingmenus',
            name='application',
        ),
        migrations.RemoveField(
            model_name='settingmenus',
            name='company',
        ),
        migrations.RemoveField(
            model_name='settingmenus',
            name='page_name',
        ),
    ]
