# Generated by Django 4.2.3 on 2023-09-09 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0044_alter_settingmenus_options_setting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
    ]
