# Generated by Django 4.2.3 on 2023-09-10 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0049_alter_settingmenus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingmenus',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='common.setting'),
        ),
    ]
