# Generated by Django 4.2.3 on 2023-09-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0050_alter_settingmenus_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingmenus',
            options={},
        ),
    ]
