# Generated by Django 4.2.3 on 2023-09-10 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0052_alter_settingmenus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingmenus',
            options={},
        ),
    ]
