# Generated by Django 4.2.3 on 2023-09-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0053_alter_settingmenus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pictures',
            field=models.ManyToManyField(blank=True, related_name='person', to='common.pictures'),
        ),
    ]
