# Generated by Django 4.2.3 on 2023-09-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0055_alter_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingmenus',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
