# Generated by Django 4.2.3 on 2023-09-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0056_settingmenus_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='_website',
            field=models.URLField(blank=True, null=True, verbose_name='Website Address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='jobs',
            field=models.ManyToManyField(to='common.jobs', verbose_name='Jobs'),
        ),
    ]
