# Generated by Django 4.2.3 on 2023-09-11 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0057_alter_person__website_alter_person_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccategory',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='academiccategory',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='academicrank',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='academicrank',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Academic Rank Name'),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='academic_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.academiccategory', verbose_name='Academic Category'),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='academic_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.academicrank', verbose_name='Academic Rank'),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='field_of_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.fieldofstudy', verbose_name='Field of Study'),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='gpa',
            field=models.FloatField(verbose_name='GPA'),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='graduation_year',
            field=models.PositiveIntegerField(verbose_name='Graduations Year'),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='medical_degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.educationaldegree', verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.university', verbose_name='University'),
        ),
        migrations.AlterField(
            model_name='educationaldegree',
            name='abbreviation',
            field=models.CharField(max_length=100, verbose_name='Degree Abbreviation'),
        ),
        migrations.AlterField(
            model_name='educationaldegree',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='educationaldegree',
            name='duration_years',
            field=models.PositiveIntegerField(verbose_name='Duration (Years)'),
        ),
        migrations.AlterField(
            model_name='educationaldegree',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Educational Degree Name'),
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Field of Study Name'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Job Name'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.roles', verbose_name='Related Role'),
        ),
        migrations.AlterField(
            model_name='places',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website Address'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Role Name'),
        ),
        migrations.AlterField(
            model_name='university',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.location', verbose_name='Geographical Location'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=200, verbose_name='University Name'),
        ),
        migrations.AlterField(
            model_name='university',
            name='website',
            field=models.URLField(verbose_name='Website Address'),
        ),
        migrations.AlterField(
            model_name='universityplaces',
            name='name',
            field=models.CharField(max_length=80, verbose_name='University region Name'),
        ),
    ]
