# Generated by Django 4.2.3 on 2023-09-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0058_alter_academiccategory_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='_ssn',
            field=models.CharField(max_length=70272, null=True),
        ),
    ]
