# Generated by Django 4.2.3 on 2023-09-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0059_alter_person__ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='_date_of_birth',
            field=models.CharField(db_column='birthdate', max_length=558, null=True, verbose_name='Birthdate'),
        ),
    ]
