# Generated by Django 4.2.3 on 2023-09-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0060_alter_person__date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='_date_of_birth',
        ),
        migrations.AddField(
            model_name='person',
            name='date_of_birth',
            field=models.CharField(db_column='birthdate', max_length=10, null=True, verbose_name='Birthdate'),
        ),
    ]
