# Generated by Django 4.2.3 on 2023-09-11 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0061_remove_person__date_of_birth_person_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='_firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='_gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='_lastname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='_mobile_phone',
            new_name='mobile_phone',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='_national_code',
            new_name='national_code',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='_nationality',
            new_name='nationality',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='_passport_number',
            new_name='passport_number',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='_profile_picture',
            new_name='profile_picture',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='_ssn',
            new_name='ssn',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='_website',
            new_name='website',
        ),
    ]
