# Generated by Django 4.2.3 on 2023-09-11 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0063_alter_settingmenus_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingmenus',
            options={'ordering': ['cat', 'index', 'parent']},
        ),
    ]
