# Generated by Django 4.2.3 on 2023-09-11 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0064_alter_settingmenus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingmenus',
            options={'ordering': ['cat']},
        ),
    ]
