# Generated by Django 4.2.3 on 2023-09-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0070_alter_classification_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='model',
            field=models.CharField(blank=True, choices=[], max_length=40, null=True, verbose_name='Model Name'),
        ),
    ]
