# Generated by Django 4.2.3 on 2023-09-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0071_alter_classification_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='model',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Model Name'),
        ),
    ]
