# Generated by Django 4.2.3 on 2023-09-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0074_alter_classification_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettingspic',
            name='name',
            field=models.CharField(blank=True, choices=[('swiper', 'Swiper'), ('prfpic', 'Profile Picture'), ('cflag', 'Contry Flag')], max_length=30, null=True),
        ),
    ]
