# Generated by Django 4.2.3 on 2023-09-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0075_alter_systemsettingspic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettingspic',
            name='app',
            field=models.CharField(blank=True, choices=[('administration', 'administration'), ('food', 'food'), ('nursing', 'nursing'), ('shopping', 'shopping'), ('tourism', 'tourism'), ('accommodation', 'accommodation'), ('transportation', 'transportation'), ('treatment', 'treatment'), ('common', 'common'), ('communication', 'communication'), ('financialhub', 'financialhub')], max_length=40, null=True),
        ),
    ]
