# Generated by Django 4.2.3 on 2023-09-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0077_remove_person_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='classification',
            field=models.ManyToManyField(blank=True, related_name='picture', to='common.classification'),
        ),
    ]
