# Generated by Django 4.2.3 on 2023-09-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0078_pictures_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='national_code',
            field=models.TextField(db_column='national_code', null=True, unique=True, verbose_name='National Code'),
        ),
    ]
