# Generated by Django 4.2.3 on 2023-09-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0079_alter_person_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='national_code',
            field=models.TextField(db_column='national_code', null=True, verbose_name='National Code'),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('nationality', 'national_code')},
        ),
    ]
