# Generated by Django 4.2.3 on 2023-09-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0080_alter_person_national_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.TextField(db_column='email', null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mobile_phone',
            field=models.TextField(db_column='mobile_phone', null=True, unique=True, verbose_name='Mobile Phone'),
        ),
    ]
