# Generated by Django 4.2.3 on 2023-09-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0083_settingmenus_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingmenus',
            name='path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
