# Generated by Django 4.2.3 on 2023-09-14 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0086_remove_settingmenus_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingmenus',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
