# Generated by Django 4.2.3 on 2023-09-14 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0089_access_creator_dateslot_creator_document_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_person', to=settings.AUTH_USER_MODEL),
        ),
    ]
