# Generated by Django 4.2.3 on 2023-09-14 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0090_person_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='classification',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='dateslot',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='document',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='location',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='person',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='role',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='settingmenus',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='creator',
        ),
    ]
