# Generated by Django 4.2.3 on 2023-09-14 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0091_remove_access_creator_remove_classification_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
