# Generated by Django 4.2.3 on 2023-09-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0093_remove_classification_creator_user_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='creator',
        ),
    ]
