# Generated by Django 4.2.5 on 2023-09-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0096_auditlog_content_type_auditlog_ipv4_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingmenus',
            name='access',
            field=models.ManyToManyField(blank=True, related_name='settingMenus', to='common.role'),
        ),
    ]
