# Generated by Django 4.2.5 on 2023-09-16 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0097_settingmenus_access'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settingmenus',
            old_name='access',
            new_name='role',
        ),
    ]
