# Generated by Django 4.2.5 on 2023-09-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0098_rename_access_settingmenus_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingmenus',
            name='tables',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
