# Generated by Django 4.2.5 on 2023-09-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0100_alter_settingmenus_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppModels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('application', models.CharField(choices=[('administration', 'administration'), ('food', 'food'), ('nursing', 'nursing'), ('shopping', 'shopping'), ('tourism', 'tourism'), ('accommodation', 'accommodation'), ('transportation', 'transportation'), ('treatment', 'treatment'), ('common', 'common'), ('communication', 'communication'), ('financialhub', 'financialhub')], max_length=255)),
                ('modelss', models.CharField(choices=[], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='settingmenus',
            name='tables',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
