# Generated by Django 4.2.5 on 2023-09-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0101_appmodels_alter_settingmenus_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmodels',
            name='application',
            field=models.CharField(choices=[('administration', 'administration'), ('food', 'food'), ('nursing', 'nursing'), ('shopping', 'shopping'), ('tourism', 'tourism'), ('accommodation', 'accommodation'), ('transportation', 'transportation'), ('treatment', 'treatment'), ('common', 'common'), ('communication', 'communication'), ('financialhub', 'financialhub')], max_length=50),
        ),
        migrations.AlterField(
            model_name='appmodels',
            name='modelss',
            field=models.CharField(max_length=70),
        ),
    ]
