# Generated by Django 4.2.5 on 2023-09-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0102_alter_appmodels_application_alter_appmodels_modelss'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmodels',
            name='temp',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
