# Generated by Django 4.2.5 on 2023-09-17 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0105_appmodels_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appmodels',
            name='temp',
        ),
    ]
