# Generated by Django 4.2.5 on 2023-09-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0106_remove_appmodels_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmodels',
            name='temp',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
