# Generated by Django 4.2.5 on 2023-09-17 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0107_appmodels_temp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appmodels',
            unique_together={('application', 'modelss')},
        ),
        migrations.RemoveField(
            model_name='appmodels',
            name='temp',
        ),
    ]
