# Generated by Django 4.2.5 on 2023-09-17 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0108_alter_appmodels_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appmodels',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='appmodels',
            name='temp',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='appmodels',
            name='application',
            field=models.CharField(choices=[('administration', 'administration'), ('food', 'food'), ('nursing', 'nursing'), ('shopping', 'shopping'), ('tourism', 'tourism'), ('accommodation', 'accommodation'), ('transportation', 'transportation'), ('treatment', 'treatment'), ('common', 'common'), ('communication', 'communication'), ('financialhub', 'financialhub')], max_length=255),
        ),
        migrations.AlterField(
            model_name='appmodels',
            name='model',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='settingmenus',
            name='tables',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setting_menus', to='common.appmodels'),
        ),
    ]
