# Generated by Django 4.2.5 on 2023-09-17 20:29

from django.db import migrations, models
# from common.models import AppModels
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0108_alter_appmodels_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appmodels',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='appmodels',
            name='application',
            field=models.CharField(choices=[('administration', 'administration'), ('food', 'food'), ('nursing', 'nursing'), ('shopping', 'shopping'), ('tourism', 'tourism'), ('accommodation', 'accommodation'), ('transportation', 'transportation'), ('treatment', 'treatment'), ('common', 'common'), ('communication', 'communication'), ('financialhub', 'financialhub')], max_length=255),
        ),
        migrations.AlterField(
            model_name='appmodels',
            name='model',
            field=models.CharField(max_length=255),
        ),
        # migrations.AlterField(
        #     model_name='settingmenus',
        #     name='tables',
        #     field=models.ManyToManyField(AppModels, related_name="setting_menus", blank = True,),
        #     preserve_default=False,
        # ),
    ]
