# Generated by Django 4.2.5 on 2023-09-17 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0109_alter_appmodels_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingmenus',  # اینجا نام مدل به درستی تایپ شده است؟
            name='tables',
            field=models.ManyToManyField(related_name='setting_menus', to='common.appmodels'),
        ),
    ]
