# Generated by Django 4.2.5 on 2023-09-17 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0110_remove_appmodels_temp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appmodels',
            old_name='modelss',
            new_name='models',
        ),
    ]
