# Generated by Django 4.2.5 on 2023-09-17 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0112_remove_settingmenus_tables_settingmenus_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingmenus',
            name='tables',
        ),
    ]
