# Generated by Django 4.2.5 on 2023-09-18 07:42

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0113_remove_settingmenus_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingmenus',
            name='tables',
            field=models.ManyToManyField(blank=True, limit_choices_to={'application': django.db.models.expressions.OuterRef('cat__application')}, related_name='setting_menus', to='common.appmodels'),
        ),
    ]
