# Generated by Django 4.2.5 on 2023-09-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0115_alter_appmodels_application_alter_appmodels_models_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appmodels',
            old_name='models',
            new_name='model',
        ),
    ]
