# Generated by Django 4.2.5 on 2023-09-19 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0116_rename_models_appmodels_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appmodels',
            unique_together={('application', 'model')},
        ),
    ]
