# Generated by Django 4.2.5 on 2023-09-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0117_alter_appmodels_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmodels',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
