# Generated by Django 4.2.5 on 2023-09-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0118_appmodels_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmodels',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
