# Generated by Django 4.2.5 on 2023-09-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0119_alter_appmodels_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingmenus',
            name='tables',
        ),
    ]
