# Generated by Django 4.2.5 on 2023-09-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0121_settingmenus_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appmodels',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appmodels',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='appmodels',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='appmodels',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
