# Generated by Django 4.2.5 on 2023-09-20 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_alter_companywebsite_url'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('common', '0124_appmodels_created_at_appmodels_deleted_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roles',
            new_name='JobRoles',
        ),
        migrations.RenameModel(
            old_name='Access',
            new_name='UserAccess',
        ),
        migrations.RenameModel(
            old_name='Role',
            new_name='UserRole',
        ),
    ]
