# Generated by Django 4.2.5 on 2023-09-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0110_alter_settingmenus_tables'),
        ('common', '0125_rename_roles_jobroles_rename_access_useraccess_and_more'),
    ]

    operations = [
    ]
