# Generated by Django 4.2.5 on 2023-09-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0128_remove_settingmenus_tables_appmodels_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingmenus',
            name='tables',
            field=models.ManyToManyField(blank=True, related_name='setting_menus', to='common.appmodels'),
        ),
    ]
