# Generated by Django 4.2.5 on 2023-09-21 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0128_remove_appmodels_modelss_appmodels_model'),
        ('common', '0129_settingmenus_tables'),
    ]

    operations = [
    ]
