# Generated by Django 4.2.5 on 2023-09-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0130_merge_20230921_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmodels',
            name='model',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
