# Generated by Django 4.2.5 on 2023-09-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0131_alter_appmodels_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
