# Generated by Django 4.2.5 on 2023-09-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0132_mycounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycounter',
            name='name',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='mycounter',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
