# Generated by Django 4.2.5 on 2023-09-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0133_mycounter_name_alter_mycounter_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycounter',
            name='value',
        ),
        migrations.AddField(
            model_name='mycounter',
            name='value_num',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mycounter',
            name='value_txt',
            field=models.TextField(null=True),
        ),
    ]
