# Generated by Django 4.2.5 on 2023-09-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0134_remove_mycounter_value_mycounter_value_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycounter',
            name='value_num',
        ),
        migrations.RemoveField(
            model_name='mycounter',
            name='value_txt',
        ),
        migrations.AddField(
            model_name='mycounter',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
