# Generated by Django 4.2.5 on 2023-09-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0135_remove_mycounter_value_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingmenus',
            name='container_tag',
            field=models.CharField(choices=[('div', 'div'), ('section', 'section'), ('article', 'article')], max_length=15, null=True),
        ),
    ]
