# Generated by Django 4.2.5 on 2023-10-12 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0138_blacklistedtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenLifetime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('lifetime', models.DurationField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='token_lifetime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.tokenlifetime'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='token_lifetime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.tokenlifetime'),
        ),
    ]
