# Generated by Django 4.2.5 on 2023-10-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0142_loginrecord_ip_validation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginrecord',
            name='browser_version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Browser Version'),
        ),
        migrations.AddField(
            model_name='loginrecord',
            name='os_version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='OS Version'),
        ),
        migrations.AlterField(
            model_name='loginrecord',
            name='browser',
            field=models.CharField(max_length=255, verbose_name='Browser'),
        ),
        migrations.AlterField(
            model_name='loginrecord',
            name='operating_system',
            field=models.CharField(max_length=255, verbose_name='Operating System'),
        ),
    ]
