# Generated by Django 4.2.5 on 2023-10-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0143_loginrecord_browser_version_loginrecord_os_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginrecord',
            name='browser',
        ),
        migrations.RemoveField(
            model_name='loginrecord',
            name='browser_version',
        ),
        migrations.RemoveField(
            model_name='loginrecord',
            name='operating_system',
        ),
        migrations.RemoveField(
            model_name='loginrecord',
            name='os_version',
        ),
        migrations.AddField(
            model_name='loginrecord',
            name='platform_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loginrecord',
            name='user_agent_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
