# Generated by Django 4.2.5 on 2023-10-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0145_location_city_location_country_location_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginrecord',
            name='ipv4_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='IPv4 Address'),
        ),
        migrations.AlterField(
            model_name='loginrecord',
            name='ipv6_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv6', verbose_name='IPv6 Address'),
        ),
    ]
