# Generated by Django 4.2.5 on 2023-10-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0146_alter_loginrecord_ipv4_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginrecord',
            name='gps_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
