# Generated by Django 4.2.5 on 2023-10-15 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0147_loginrecord_gps_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS Latitude'),
        ),
        migrations.AddField(
            model_name='location',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS Longitude'),
        ),
        migrations.AlterField(
            model_name='loginrecord',
            name='gps_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_login_record', to='common.location', verbose_name='GPS Location'),
        ),
    ]
