# Generated by Django 4.2.5 on 2023-10-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0148_location_gps_latitude_location_gps_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ]
