# Generated by Django 4.2.5 on 2023-10-16 15:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0152_remove_user_bio_remove_user_mobile_number_person_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mobile_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_column='mobile_phone', max_length=15, null=True, region=None, unique=True, verbose_name='Mobile Phone'),
        ),
    ]
