# Generated by Django 4.2.5 on 2023-10-16 15:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0153_alter_person_mobile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mobile_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
