# Generated by Django 4.2.5 on 2023-10-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0156_remove_loginrecord_platform_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmodels',
            name='application',
            field=models.CharField(choices=[('administration', 'administration'), ('food', 'food'), ('nursing', 'nursing'), ('shopping', 'shopping'), ('tourism', 'tourism'), ('accommodation', 'accommodation'), ('transportation', 'transportation'), ('treatment', 'treatment'), ('common', 'common'), ('communication', 'communication'), ('financialhub', 'financialhub'), ('rest_framework', 'rest_framework'), ('rest_framework_simplejwt', 'rest_framework_simplejwt'), ('sslserver', 'sslserver')], max_length=50),
        ),
        migrations.AlterField(
            model_name='classification',
            name='app',
            field=models.CharField(blank=True, choices=[('administration', 'administration'), ('food', 'food'), ('nursing', 'nursing'), ('shopping', 'shopping'), ('tourism', 'tourism'), ('accommodation', 'accommodation'), ('transportation', 'transportation'), ('treatment', 'treatment'), ('common', 'common'), ('communication', 'communication'), ('financialhub', 'financialhub'), ('rest_framework', 'rest_framework'), ('rest_framework_simplejwt', 'rest_framework_simplejwt'), ('sslserver', 'sslserver')], max_length=50, null=True, verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='application',
            field=models.CharField(choices=[('administration', 'administration'), ('food', 'food'), ('nursing', 'nursing'), ('shopping', 'shopping'), ('tourism', 'tourism'), ('accommodation', 'accommodation'), ('transportation', 'transportation'), ('treatment', 'treatment'), ('common', 'common'), ('communication', 'communication'), ('financialhub', 'financialhub'), ('rest_framework', 'rest_framework'), ('rest_framework_simplejwt', 'rest_framework_simplejwt'), ('sslserver', 'sslserver')], max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsettingspic',
            name='app',
            field=models.CharField(blank=True, choices=[('administration', 'administration'), ('food', 'food'), ('nursing', 'nursing'), ('shopping', 'shopping'), ('tourism', 'tourism'), ('accommodation', 'accommodation'), ('transportation', 'transportation'), ('treatment', 'treatment'), ('common', 'common'), ('communication', 'communication'), ('financialhub', 'financialhub'), ('rest_framework', 'rest_framework'), ('rest_framework_simplejwt', 'rest_framework_simplejwt'), ('sslserver', 'sslserver')], max_length=50, null=True),
        ),
    ]
