# Generated by Django 4.2.5 on 2023-10-23 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0158_alter_appmodels_application_alter_classification_app_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteManagementsLog',
            new_name='SiteManagementLog',
        ),
    ]
