# Generated by Django 4.2.5 on 2023-12-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0163_alter_academiccategory_id_alter_academicrank_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingmenus',
            name='container_tag',
            field=models.CharField(choices=[('div', 'div'), ('section', 'section'), ('article', 'article'), ('', '')], max_length=15, null=True),
        ),
    ]
