# Generated by Django 4.2.5 on 2023-12-22 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0168_alter_academiccategory_id_alter_academicrank_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
    ]
