# Generated by Django 4.2.5 on 2023-12-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0171_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='appmodels',
            name='application',
            field=models.CharField(choices=[('administration', 'administration'), ('food', 'food'), ('nursing', 'nursing'), ('shopping', 'shopping'), ('tourism', 'tourism'), ('accommodation', 'accommodation'), ('transportation', 'transportation'), ('treatment', 'treatment'), ('common', 'common'), ('communication', 'communication'), ('financialhub', 'financialhub'), ('safedelete', 'safedelete'), ('rest_framework', 'rest_framework'), ('rest_framework_simplejwt', 'rest_framework_simplejwt'), ('sslserver', 'sslserver'), ('corsheaders', 'corsheaders'), ('rest_framework_simplejwt.token_blacklist', 'rest_framework_simplejwt.token_blacklist')], max_length=50),
        ),
        migrations.AlterField(
            model_name='classification',
            name='app',
            field=models.CharField(blank=True, choices=[('administration', 'administration'), ('food', 'food'), ('nursing', 'nursing'), ('shopping', 'shopping'), ('tourism', 'tourism'), ('accommodation', 'accommodation'), ('transportation', 'transportation'), ('treatment', 'treatment'), ('common', 'common'), ('communication', 'communication'), ('financialhub', 'financialhub'), ('safedelete', 'safedelete'), ('rest_framework', 'rest_framework'), ('rest_framework_simplejwt', 'rest_framework_simplejwt'), ('sslserver', 'sslserver'), ('corsheaders', 'corsheaders'), ('rest_framework_simplejwt.token_blacklist', 'rest_framework_simplejwt.token_blacklist')], max_length=50, null=True, verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='application',
            field=models.CharField(choices=[('administration', 'administration'), ('food', 'food'), ('nursing', 'nursing'), ('shopping', 'shopping'), ('tourism', 'tourism'), ('accommodation', 'accommodation'), ('transportation', 'transportation'), ('treatment', 'treatment'), ('common', 'common'), ('communication', 'communication'), ('financialhub', 'financialhub'), ('safedelete', 'safedelete'), ('rest_framework', 'rest_framework'), ('rest_framework_simplejwt', 'rest_framework_simplejwt'), ('sslserver', 'sslserver'), ('corsheaders', 'corsheaders'), ('rest_framework_simplejwt.token_blacklist', 'rest_framework_simplejwt.token_blacklist')], max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsettingspic',
            name='app',
            field=models.CharField(blank=True, choices=[('administration', 'administration'), ('food', 'food'), ('nursing', 'nursing'), ('shopping', 'shopping'), ('tourism', 'tourism'), ('accommodation', 'accommodation'), ('transportation', 'transportation'), ('treatment', 'treatment'), ('common', 'common'), ('communication', 'communication'), ('financialhub', 'financialhub'), ('safedelete', 'safedelete'), ('rest_framework', 'rest_framework'), ('rest_framework_simplejwt', 'rest_framework_simplejwt'), ('sslserver', 'sslserver'), ('corsheaders', 'corsheaders'), ('rest_framework_simplejwt.token_blacklist', 'rest_framework_simplejwt.token_blacklist')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
