# Generated by Django 4.2.5 on 2023-12-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('common', '0175_user_description_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='group_ptr',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='token_lifetime',
        ),
        migrations.AlterField(
            model_name='settingmenus',
            name='role',
            field=models.ManyToManyField(blank=True, related_name='settingMenus', to='auth.group'),
        ),
        migrations.DeleteModel(
            name='UserAccess',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
