# Generated by Django 4.2.5 on 2023-12-25 19:42

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0178_alter_appmodels_application_alter_classification_app_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTableTest2',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('firstname', models.TextField(db_column='firstname', null=True, verbose_name='نام')),
                ('lastname', models.TextField(db_column='lastname', null=True, verbose_name='نام خانوادگی')),
                ('national_code', models.TextField(db_column='national_code', null=True, verbose_name='شماره ملی')),
                ('date_of_birth', models.CharField(db_column='birthdate', max_length=10, null=True, verbose_name='تاریخ تولد')),
                ('gender', models.CharField(choices=[('Male', 'مرد'), ('Female', 'زن')], db_column='gender', max_length=10, null=True, verbose_name='جنسیت')),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='شماره همراه')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('address', models.ManyToManyField(blank=True, to='common.places', verbose_name='نشانی')),
                ('jobs', models.ManyToManyField(to='common.jobs', verbose_name='شغل')),
                ('pictures', models.ManyToManyField(blank=True, to='common.pictures', verbose_name='عکس')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DynamicTableTest1',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('firstname', models.TextField(db_column='firstname', null=True, verbose_name='First Name')),
                ('lastname', models.TextField(db_column='lastname', null=True, verbose_name='Last Name')),
                ('date_of_birth', models.CharField(db_column='birthdate', max_length=10, null=True, verbose_name='Birthdate')),
                ('national_code', models.TextField(db_column='national_code', null=True, verbose_name='National Code')),
                ('ssn', models.CharField(max_length=12, null=True)),
                ('passport_number', models.TextField(db_column='passport_number', null=True, verbose_name='Passport Number')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], db_column='gender', max_length=10, null=True, verbose_name='Gender')),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=255, null=True, unique=True, verbose_name='email address')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website Address')),
                ('nationality', models.TextField(db_column='nationality', null=True, verbose_name='Nationality')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='About Me')),
                ('address', models.ManyToManyField(blank=True, to='common.places')),
                ('jobs', models.ManyToManyField(to='common.jobs', verbose_name='Jobs')),
                ('pictures', models.ManyToManyField(blank=True, to='common.pictures')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
