# Generated by Django 4.2.5 on 2023-12-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('common', '0179_dynamictabletest2_dynamictabletest1'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingmenus',
            name='individual_permission',
            field=models.ManyToManyField(blank=True, related_name='setting_menus', to='auth.permission'),
        ),
    ]
