# Generated by Django 4.2.5 on 2023-12-26 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0179_dynamictabletest2_dynamictabletest1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingmenus',
            name='tables',
        ),
    ]
