# Generated by Django 4.2.5 on 2023-12-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('common', '0181_settingmenus_individual_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingmenus',
            name='tables',
            field=models.ManyToManyField(blank=True, related_name='setting_menus', to='contenttypes.contenttype'),
        ),
    ]
