# Generated by Django 4.2.5 on 2023-12-26 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0182_settingmenus_individual_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingmenus',
            name='tables',
        ),
    ]
