# Generated by Django 4.2.5 on 2023-12-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0183_remove_settingmenus_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingmenus',
            name='tables',
            field=models.ManyToManyField(blank=True, related_name='setting_menus', to='common.appmodels'),
        ),
    ]
