# Generated by Django 4.2.5 on 2023-12-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0184_settingmenus_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingmenus',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Website Address'),
        ),
    ]
