# Generated by Django 4.2.5 on 2023-12-26 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0184_settingmenus_individual_permission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingmenus',
            name='individual_permission',
        ),
    ]
