# Generated by Django 4.2.5 on 2023-12-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0185_settingmenus_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingmenus',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
