# Generated by Django 4.2.5 on 2023-12-30 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0186_settingmenus_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='settingmenus',
            unique_together={('cat', 'index', 'name', 'parent', 'deleted_at')},
        ),
    ]
