# Generated by Django 4.2.5 on 2023-12-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0187_alter_settingmenus_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingmenus',
            name='order',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
