# Generated by Django 4.2.5 on 2023-12-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0188_alter_settingmenus_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingmenus',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
