# Generated by Django 4.2.5 on 2024-01-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0189_alter_settingmenus_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmodels',
            name='application',
            field=models.CharField(choices=[('administration', 'administration'), ('food', 'food'), ('nursing', 'nursing'), ('shopping', 'shopping'), ('tourism', 'tourism'), ('accommodation', 'accommodation'), ('transportation', 'transportation'), ('treatment', 'treatment'), ('common', 'common'), ('communication', 'communication'), ('financialhub', 'financialhub'), ('safedelete', 'safedelete'), ('django_extensions', 'django_extensions'), ('rest_framework', 'rest_framework'), ('rest_framework_simplejwt', 'rest_framework_simplejwt'), ('sslserver', 'sslserver'), ('corsheaders', 'corsheaders'), ('token_blacklist', 'token_blacklist'), ('admin', 'admin'), ('auth', 'auth'), ('contenttypes', 'contenttypes'), ('sessions', 'sessions'), ('messages', 'messages'), ('runserver_nostatic', 'runserver_nostatic'), ('staticfiles', 'staticfiles'), ('django_user_agents', 'django_user_agents')], max_length=50),
        ),
        migrations.AlterField(
            model_name='classification',
            name='app',
            field=models.CharField(blank=True, choices=[('administration', 'administration'), ('food', 'food'), ('nursing', 'nursing'), ('shopping', 'shopping'), ('tourism', 'tourism'), ('accommodation', 'accommodation'), ('transportation', 'transportation'), ('treatment', 'treatment'), ('common', 'common'), ('communication', 'communication'), ('financialhub', 'financialhub'), ('safedelete', 'safedelete'), ('django_extensions', 'django_extensions'), ('rest_framework', 'rest_framework'), ('rest_framework_simplejwt', 'rest_framework_simplejwt'), ('sslserver', 'sslserver'), ('corsheaders', 'corsheaders'), ('token_blacklist', 'token_blacklist'), ('admin', 'admin'), ('auth', 'auth'), ('contenttypes', 'contenttypes'), ('sessions', 'sessions'), ('messages', 'messages'), ('runserver_nostatic', 'runserver_nostatic'), ('staticfiles', 'staticfiles'), ('django_user_agents', 'django_user_agents')], max_length=50, null=True, verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='application',
            field=models.CharField(choices=[('administration', 'administration'), ('food', 'food'), ('nursing', 'nursing'), ('shopping', 'shopping'), ('tourism', 'tourism'), ('accommodation', 'accommodation'), ('transportation', 'transportation'), ('treatment', 'treatment'), ('common', 'common'), ('communication', 'communication'), ('financialhub', 'financialhub'), ('safedelete', 'safedelete'), ('django_extensions', 'django_extensions'), ('rest_framework', 'rest_framework'), ('rest_framework_simplejwt', 'rest_framework_simplejwt'), ('sslserver', 'sslserver'), ('corsheaders', 'corsheaders'), ('token_blacklist', 'token_blacklist'), ('admin', 'admin'), ('auth', 'auth'), ('contenttypes', 'contenttypes'), ('sessions', 'sessions'), ('messages', 'messages'), ('runserver_nostatic', 'runserver_nostatic'), ('staticfiles', 'staticfiles'), ('django_user_agents', 'django_user_agents')], max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsettingspic',
            name='app',
            field=models.CharField(blank=True, choices=[('administration', 'administration'), ('food', 'food'), ('nursing', 'nursing'), ('shopping', 'shopping'), ('tourism', 'tourism'), ('accommodation', 'accommodation'), ('transportation', 'transportation'), ('treatment', 'treatment'), ('common', 'common'), ('communication', 'communication'), ('financialhub', 'financialhub'), ('safedelete', 'safedelete'), ('django_extensions', 'django_extensions'), ('rest_framework', 'rest_framework'), ('rest_framework_simplejwt', 'rest_framework_simplejwt'), ('sslserver', 'sslserver'), ('corsheaders', 'corsheaders'), ('token_blacklist', 'token_blacklist'), ('admin', 'admin'), ('auth', 'auth'), ('contenttypes', 'contenttypes'), ('sessions', 'sessions'), ('messages', 'messages'), ('runserver_nostatic', 'runserver_nostatic'), ('staticfiles', 'staticfiles'), ('django_user_agents', 'django_user_agents')], max_length=50, null=True),
        ),
    ]
