# Generated by Django 4.1.5 on 2023-07-27 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0017_alter_person__birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام آلرژی')),
                ('description', models.TextField(verbose_name='توضیحات آلرژی')),
            ],
        ),
        migrations.CreateModel(
            name='ImmunologyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام آزمایش')),
                ('result', models.CharField(max_length=100, verbose_name='نتیجه آزمایش')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(verbose_name='تاریخ ویزیت')),
                ('symptoms', models.TextField(verbose_name='علائم بیماری')),
                ('diagnosis', models.TextField(verbose_name='تشخیص بیماری')),
                ('prescriptions', models.TextField(verbose_name='دستورات پزشک')),
                ('hospitalization', models.BooleanField(default=False, verbose_name='بستری شده؟')),
                ('surgery', models.TextField(blank=True, null=True, verbose_name='جراحی و اقدامات جراحی')),
                ('post_treatment', models.TextField(blank=True, null=True, verbose_name='اقدامات بعد از درمان')),
                ('allergies', models.ManyToManyField(blank=True, to='treatment.allergy', verbose_name='آلرژی\u200cها')),
                ('paraclinical_tests', models.ManyToManyField(blank=True, to='treatment.immunologytest', verbose_name='آزمایش\u200cهای ایمونولوژی')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.person', verbose_name='بیمار')),
            ],
        ),
    ]
