# Generated by Django 4.2.3 on 2023-08-16 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financialhub', '0001_initial'),
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='medical_center',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='procedure',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_procedures', to='treatment.specialty', verbose_name='تخصص مرتبط'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='subspecialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_procedure', to='treatment.subspecialty', verbose_name='زیرتخصص مرتبط'),
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='cost',
        ),
        migrations.AlterField(
            model_name='procedure',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام فرآیند درمانی'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='cost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_procedure', to='financialhub.cost', verbose_name='هزینه (در واحد پولی)'),
        ),
    ]
