# Generated by Django 4.1.5 on 2023-07-27 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_alter_person__birthdate'),
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliatedWith',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createddtm', models.DateTimeField(auto_now_add=True)),
                ('updatedtm', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('physician', models.IntegerField()),
                ('department', models.IntegerField()),
                ('primaryaffiliation', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppBookingChannel',
            fields=[
                ('createddtm', models.DateTimeField(auto_now_add=True)),
                ('updatedtm', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app_booking_channel_name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('createddtm', models.DateTimeField(auto_now_add=True)),
                ('updatedtm', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_account_id', models.IntegerField()),
                ('office_id', models.IntegerField()),
                ('probable_start_time', models.DateTimeField()),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('appointment_status_id', models.IntegerField()),
                ('appointment_taken_date', models.DateField()),
                ('app_booking_channel_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppointmentStatus',
            fields=[
                ('createddtm', models.DateTimeField(auto_now_add=True)),
                ('updatedtm', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('createddtm', models.DateTimeField(auto_now_add=True)),
                ('updatedtm', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('professional_statement', models.TextField()),
                ('practicing_from', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HealthCenter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createddtm', models.DateTimeField(auto_now_add=True)),
                ('updatedtm', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createddtm', models.DateTimeField(auto_now_add=True)),
                ('updatedtm', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('healthCenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to='treatment.healthcenter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createddtm', models.DateTimeField(auto_now_add=True)),
                ('updatedtm', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('employeeid', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('registered', models.BooleanField()),
                ('ssn', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createddtm', models.DateTimeField(auto_now_add=True)),
                ('updatedtm', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createddtm', models.DateTimeField(auto_now_add=True)),
                ('updatedtm', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('ssn', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=255)),
                ('insuranceid', models.IntegerField()),
                ('pcp', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prescribes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createddtm', models.DateTimeField(auto_now_add=True)),
                ('updatedtm', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('physician', models.IntegerField()),
                ('patient', models.IntegerField()),
                ('medication', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('appointment', models.IntegerField()),
                ('dose', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createddtm', models.DateTimeField(auto_now_add=True)),
                ('updatedtm', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('roomnumber', models.IntegerField(unique=True)),
                ('roomtype', models.CharField(max_length=255)),
                ('blockfloor', models.IntegerField()),
                ('blockcode', models.IntegerField()),
                ('unavailable', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellRepresentation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createddtm', models.DateTimeField(auto_now_add=True)),
                ('updatedtm', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('person', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('createddtm', models.DateTimeField(auto_now_add=True)),
                ('updatedtm', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('specialization_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createddtm', models.DateTimeField(auto_now_add=True)),
                ('updatedtm', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(choices=[], max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TreatmentPackage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createddtm', models.DateTimeField(auto_now_add=True)),
                ('updatedtm', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatmentPackage', to='treatment.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainedIn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createddtm', models.DateTimeField(auto_now_add=True)),
                ('updatedtm', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('physician', models.IntegerField()),
                ('treatment', models.IntegerField()),
                ('certificationdate', models.DateField()),
                ('certificationexpires', models.DateField()),
                ('Hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainedIn', to='treatment.hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createddtm', models.DateTimeField(auto_now_add=True)),
                ('updatedtm', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('stayid', models.IntegerField(unique=True)),
                ('patient', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.room')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('createddtm', models.DateTimeField(auto_now_add=True)),
                ('updatedtm', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qualification_name', models.CharField(max_length=200)),
                ('institute_name', models.CharField(max_length=200)),
                ('procurement_year', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.doctor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createddtm', models.DateTimeField(auto_now_add=True)),
                ('updatedtm', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('cost', models.FloatField()),
                ('Hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure', to='treatment.hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParaClinic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createddtm', models.DateTimeField(auto_now_add=True)),
                ('updatedtm', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('healthCenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paraClinic', to='treatment.healthcenter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HospitalAffiliation',
            fields=[
                ('createddtm', models.DateTimeField(auto_now_add=True)),
                ('updatedtm', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.doctor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='healthcenter',
            name='treatmentPackage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healthCenter', to='treatment.treatmentpackage'),
        ),
        migrations.CreateModel(
            name='DoctorSpecialization',
            fields=[
                ('createddtm', models.DateTimeField(auto_now_add=True)),
                ('updatedtm', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor', models.IntegerField()),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.specialization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createddtm', models.DateTimeField(auto_now_add=True)),
                ('updatedtm', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('medical_history', models.TextField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='common.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createddtm', models.DateTimeField(auto_now_add=True)),
                ('updatedtm', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('healthCenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healthCenter', to='treatment.healthcenter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
