# Generated by Django 4.2.3 on 2023-08-16 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financialhub', '0001_initial'),
        ('treatment', '0002_remove_procedure_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcenterunit',
            name='cost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_medical_center_unit', to='financialhub.cost', verbose_name='هزینه (در واحد پولی)'),
        ),
        migrations.AddField(
            model_name='physician',
            name='cost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_physician', to='financialhub.cost', verbose_name='هزینه (در واحد پولی)'),
        ),
        migrations.AddField(
            model_name='physician',
            name='qualification',
            field=models.ManyToManyField(related_name='physician', to='treatment.qualification'),
        ),
    ]
