# Generated by Django 4.1.5 on 2023-07-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0002_affiliatedwith_appbookingchannel_appointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[], max_length=100)),
                ('class_name', models.CharField(choices=[], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Specialties',
        ),
    ]
