# Generated by Django 4.1.5 on 2023-07-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0003_specialty_delete_specialties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='class_name',
            field=models.CharField(choices=[('Allergy and Immunology', 'allergy_and_immunology')], max_length=100),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(choices=[('Allergy and Immunology', 'allergy_and_immunology')], max_length=100),
        ),
    ]
