# Generated by Django 4.2.3 on 2023-08-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0003_medicalcenterunit_cost_physician_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physician',
            name='certification_date',
        ),
    ]
