# Generated by Django 4.2.3 on 2023-07-30 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_rename__address_person_address_alter_places_manager'),
        ('treatment', '0003_alter_sellrepresentation_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellrepresentation',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sell_representation', to='common.person'),
        ),
    ]
