# Generated by Django 4.2.3 on 2023-08-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0004_remove_physician_certification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldegree',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='نام مدرک'),
        ),
    ]
