# Generated by Django 4.1.5 on 2023-07-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0005_alter_specialty_class_name_alter_specialty_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='class_name',
            field=models.CharField(choices=[('Allergy and Immunology', 'allergy_and_immunology')], max_length=100),
        ),
    ]
