# Generated by Django 4.1.5 on 2023-07-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0006_alter_specialty_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='branches',
            field=models.CharField(choices=[('Allergy and Immunology', 'Allergy and Immunology')], max_length=100, null=True),
        ),
    ]
