# Generated by Django 4.2.3 on 2023-08-16 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0006_medicaldegree_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subspecialty',
            name='abbreviation',
            field=models.CharField(max_length=20, verbose_name='مخفف فوق\u200cتخصص'),
        ),
        migrations.AlterField(
            model_name='subspecialty',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.medicaldegree', verbose_name='مدرک فوق\u200cتخصص'),
        ),
    ]
