# Generated by Django 4.2.3 on 2023-08-17 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_academiccategory_academicrank_university_and_more'),
        ('treatment', '0008_alter_procedure_name_alter_specialty_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='subspecialty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subspecialty',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='subspecialty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='physician',
            name='medical_degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physicians', to='common.academicrecord'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.educationaldegree', verbose_name='مدرک تخصص'),
        ),
        migrations.AlterField(
            model_name='subspecialty',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.educationaldegree', verbose_name='مدرک فوق\u200cتخصص'),
        ),
        migrations.AlterField(
            model_name='subspecialty',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='MedicalDegree',
        ),
    ]
