# Generated by Django 4.2.3 on 2023-08-25 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_remove_document_classification'),
        ('nursing', '0001_initial'),
        ('administration', '0003_company_description_company_document_company_name'),
        ('treatment', '0009_procedure_created_at_procedure_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialtyCompany',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('Specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.specialty')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.company')),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.person')),
                ('nurse', models.ManyToManyField(related_name='specialty_company', to='nursing.nurses')),
                ('physician', models.ManyToManyField(related_name='specialty_company', to='treatment.physician')),
                ('qualification', models.ManyToManyField(related_name='specialty_companey', to='treatment.qualification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='specialty',
            name='company',
            field=models.ManyToManyField(through='treatment.SpecialtyCompany', to='administration.company'),
        ),
    ]
