# Generated by Django 4.2.3 on 2023-08-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_remove_document_classification'),
        ('treatment', '0010_specialtycompany_specialty_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='document',
            field=models.ManyToManyField(related_name='common_qualification', to='common.document'),
        ),
    ]
