# Generated by Django 4.2.3 on 2023-08-25 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_company_description_company_document_company_name'),
        ('common', '0020_remove_document_classification'),
        ('treatment', '0011_qualification_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physician',
            name='specialties',
        ),
        migrations.RemoveField(
            model_name='physician',
            name='subspecialty',
        ),
        migrations.AddField(
            model_name='specialty',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.person'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='treatment.qualification'),
        ),
        migrations.AddField(
            model_name='subspecialty',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subspecialty', to='administration.company'),
        ),
        migrations.AddField(
            model_name='subspecialty',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.person'),
        ),
        migrations.AddField(
            model_name='subspecialty',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subspecialty',
            name='qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='treatment.qualification'),
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='company',
        ),
        migrations.DeleteModel(
            name='SpecialtyCompany',
        ),
        migrations.AddField(
            model_name='specialty',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialty', to='administration.company'),
        ),
    ]
