# Generated by Django 4.2.3 on 2023-08-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing', '0001_initial'),
        ('treatment', '0012_remove_physician_specialties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='nurse',
            field=models.ManyToManyField(related_name='specialty_company', to='nursing.nurses'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='physician',
            field=models.ManyToManyField(related_name='specialty_company', to='treatment.physician'),
        ),
    ]
