# Generated by Django 4.2.3 on 2023-08-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing', '0001_initial'),
        ('treatment', '0013_specialty_nurse_specialty_physician'),
    ]

    operations = [
        migrations.AddField(
            model_name='subspecialty',
            name='nurse',
            field=models.ManyToManyField(related_name='subspecialty_company', to='nursing.nurses'),
        ),
        migrations.AddField(
            model_name='subspecialty',
            name='physician',
            field=models.ManyToManyField(related_name='subspecialty_company', to='treatment.physician'),
        ),
    ]
