# Generated by Django 4.2.3 on 2023-08-25 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_company_description_company_document_company_name'),
        ('common', '0020_remove_document_classification'),
        ('treatment', '0014_subspecialty_nurse_subspecialty_physician'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='classification',
            field=models.ManyToManyField(related_name='procedure', to='common.classification'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.company'),
        ),
    ]
