# Generated by Django 4.2.3 on 2023-08-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0015_procedure_classification_procedure_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
