# Generated by Django 4.2.3 on 2023-08-25 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0016_medicalrecord_created_at_medicalrecord_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.allergy')),
            ],
        ),
    ]
