# Generated by Django 4.2.3 on 2023-08-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0017_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
