# Generated by Django 4.2.3 on 2023-08-26 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0022_dietassessment_nutrition_and_dietetics_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentFollowUp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('follow_up_date', models.DateTimeField(verbose_name='تاریخ پیگیری')),
                ('follow_up_notes', models.TextField(verbose_name='یادداشت\u200cهای پیگیری')),
                ('next_steps', models.TextField(verbose_name='مراحل بعدی')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_follow_ups', to='treatment.nutrition_consultant_patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
