# Generated by Django 4.2.3 on 2023-08-26 18:29

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_remove_user_group_delete_groupsuser'),
        ('treatment', '0023_treatmentfollowup'),
    ]

    operations = [
        migrations.CreateModel(
            name='medical_technology_Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_technology_Patient', to='common.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalDevice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام دستگاه پزشکی')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='تولیدکننده')),
                ('model', models.CharField(max_length=100, verbose_name='مدل دستگاه')),
                ('serial_number', models.CharField(max_length=100, verbose_name='شماره سریال')),
                ('purchase_date', models.DateField(verbose_name='تاریخ خرید')),
                ('warranty_expiration', models.DateField(verbose_name='انقضای گارانتی')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='sellrepresentation',
            name='specialties',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Adult Cardiovascular Surgery', 'Adult Cardiovascular Surgery'), ('Adult Endocrinology', 'Adult Endocrinology'), ('Adult Gastroenterology', 'Adult Gastroenterology'), ('Adult General Surgery', 'Adult General Surgery'), ('Adult Hematology', 'Adult Hematology'), ('Adult Infectious Disease', 'Adult Infectious Disease'), ('Adult Nephrology', 'Adult Nephrology'), ('Adult Neurosurgery', 'Adult Neurosurgery'), ('Adult Oncology', 'Adult Oncology'), ('Adult Orthopedics', 'Adult Orthopedics'), ('Adult Otolaryngology', 'Adult Otolaryngology'), ('Adult Plastic Surgery', 'Adult Plastic Surgery'), ('Adult Pulmonology', 'Adult Pulmonology'), ('Adult Rheumatology', 'Adult Rheumatology'), ('Allergy and Immunology', 'Allergy and Immunology'), ('Anesthesiology', 'Anesthesiology'), ('Behavioral Therapy Specialist', 'Behavioral Therapy Specialist'), ('Body Contouring Surgery', 'Body Contouring Surgery'), ('Breast Body Contouring Surgery', 'Breast Body Contouring Surgery'), ('Breast Cosmetic Surgery', 'Breast Cosmetic Surgery'), ('Breast Craniofacial Surgery', 'Breast Craniofacial Surgery'), ('Breast Reconstruction Surgery', 'Breast Reconstruction Surgery'), ('Breast Surgery', 'Breast Surgery'), ('Breathing Exercise Specialist', 'Breathing Exercise Specialist'), ('Burn Surgery', 'Burn Surgery'), ('Colorectal Surgery', 'Colorectal Surgery'), ('Cosmetic Plastic Surgery', 'Cosmetic Plastic Surgery'), ('Craniofacial Surgery', 'Craniofacial Surgery'), ('Dental Hygiene Specialist', 'Dental Hygiene Specialist'), ('Dermatologic Surgery', 'Dermatologic Surgery'), ('Dermatology', 'Dermatology'), ('Diagnostic Radiology', 'Diagnostic Radiology'), ('Emergency Medicine', 'Emergency Medicine'), ('Facial Plastic Surgery', 'Facial Plastic Surgery'), ('Family Medicine', 'Family Medicine'), ('Fitness Trainer', 'Fitness Trainer'), ('Hand Nerve Surgery', 'Hand Nerve Surgery'), ('Hand Plastic Surgery', 'Hand Plastic Surgery'), ('Hand Surgery', 'Hand Surgery'), ('Head and Neck Surgery', 'Head and Neck Surgery'), ('Healthcare Social Worker', 'Healthcare Social Worker'), ('Health Psychology Specialist', 'Health Psychology Specialist'), ('Internal Medicine', 'Internal Medicine'), ('Lower Extremity Plastic Surgery', 'Lower Extremity Plastic Surgery'), ('Massage Therapist', 'Massage Therapist'), ('Medical Genetics', 'Medical Genetics'), ('Medical Technology', 'Medical Technology'), ('Neurological Plastic Surgery', 'Neurological Plastic Surgery'), ('Neurology', 'Neurology'), ('Nuclear Medicine', 'Nuclear Medicine'), ('Nutrition and Dietetics', 'Nutrition and Dietetics'), ('Nutrition Consultant', 'Nutrition Consultant'), ('Obstetrics and Gynecology', 'Obstetrics and Gynecology'), ('Oncologic Plastic Surgery', 'Oncologic Plastic Surgery'), ('Ophthalmology', 'Ophthalmology'), ('Pathology', 'Pathology'), ('Pediatrics', 'Pediatrics'), ('Pediatric Cardiovascular Surgery', 'Pediatric Cardiovascular Surgery'), ('Pediatric Endocrinology', 'Pediatric Endocrinology'), ('Pediatric Gastroenterology', 'Pediatric Gastroenterology'), ('Pediatric General Surgery', 'Pediatric General Surgery'), ('Pediatric Hematology', 'Pediatric Hematology'), ('Pediatric Infectious Disease', 'Pediatric Infectious Disease'), ('Pediatric Nephrology', 'Pediatric Nephrology'), ('Pediatric Neurosurgery', 'Pediatric Neurosurgery'), ('Pediatric Oncology', 'Pediatric Oncology'), ('Pediatric Orthopedics', 'Pediatric Orthopedics'), ('Pediatric Otolaryngology', 'Pediatric Otolaryngology'), ('Pediatric Plastic Surgery', 'Pediatric Plastic Surgery'), ('Pediatric Pulmonology', 'Pediatric Pulmonology'), ('Pediatric Rheumatology', 'Pediatric Rheumatology'), ('Physical Medicine and Rehabilitation', 'Physical Medicine and Rehabilitation'), ('Plastic Surgery', 'Plastic Surgery'), ('Preventive Medicine', 'Preventive Medicine'), ('Psychiatry', 'Psychiatry'), ('Radiation Oncology', 'Radiation Oncology'), ('Reconstructive Plastic Surgery', 'Reconstructive Plastic Surgery'), ('Respiratory Plastic Surgery', 'Respiratory Plastic Surgery'), ('Surgery', 'Surgery'), ('Thoracic Surgery', 'Thoracic Surgery'), ('Upper Extremity Plastic Surgery', 'Upper Extremity Plastic Surgery'), ('Urogenital Plastic Surgery', 'Urogenital Plastic Surgery'), ('Urology', 'Urology'), ('Vascular Surgery', 'Vascular Surgery'), ('Yoga and Mindfulness Specialist', 'Yoga and Mindfulness Specialist')], max_length=60, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(choices=[('Adult Cardiovascular Surgery', 'Adult Cardiovascular Surgery'), ('Adult Endocrinology', 'Adult Endocrinology'), ('Adult Gastroenterology', 'Adult Gastroenterology'), ('Adult General Surgery', 'Adult General Surgery'), ('Adult Hematology', 'Adult Hematology'), ('Adult Infectious Disease', 'Adult Infectious Disease'), ('Adult Nephrology', 'Adult Nephrology'), ('Adult Neurosurgery', 'Adult Neurosurgery'), ('Adult Oncology', 'Adult Oncology'), ('Adult Orthopedics', 'Adult Orthopedics'), ('Adult Otolaryngology', 'Adult Otolaryngology'), ('Adult Plastic Surgery', 'Adult Plastic Surgery'), ('Adult Pulmonology', 'Adult Pulmonology'), ('Adult Rheumatology', 'Adult Rheumatology'), ('Allergy and Immunology', 'Allergy and Immunology'), ('Anesthesiology', 'Anesthesiology'), ('Behavioral Therapy Specialist', 'Behavioral Therapy Specialist'), ('Body Contouring Surgery', 'Body Contouring Surgery'), ('Breast Body Contouring Surgery', 'Breast Body Contouring Surgery'), ('Breast Cosmetic Surgery', 'Breast Cosmetic Surgery'), ('Breast Craniofacial Surgery', 'Breast Craniofacial Surgery'), ('Breast Reconstruction Surgery', 'Breast Reconstruction Surgery'), ('Breast Surgery', 'Breast Surgery'), ('Breathing Exercise Specialist', 'Breathing Exercise Specialist'), ('Burn Surgery', 'Burn Surgery'), ('Colorectal Surgery', 'Colorectal Surgery'), ('Cosmetic Plastic Surgery', 'Cosmetic Plastic Surgery'), ('Craniofacial Surgery', 'Craniofacial Surgery'), ('Dental Hygiene Specialist', 'Dental Hygiene Specialist'), ('Dermatologic Surgery', 'Dermatologic Surgery'), ('Dermatology', 'Dermatology'), ('Diagnostic Radiology', 'Diagnostic Radiology'), ('Emergency Medicine', 'Emergency Medicine'), ('Facial Plastic Surgery', 'Facial Plastic Surgery'), ('Family Medicine', 'Family Medicine'), ('Fitness Trainer', 'Fitness Trainer'), ('Hand Nerve Surgery', 'Hand Nerve Surgery'), ('Hand Plastic Surgery', 'Hand Plastic Surgery'), ('Hand Surgery', 'Hand Surgery'), ('Head and Neck Surgery', 'Head and Neck Surgery'), ('Healthcare Social Worker', 'Healthcare Social Worker'), ('Health Psychology Specialist', 'Health Psychology Specialist'), ('Internal Medicine', 'Internal Medicine'), ('Lower Extremity Plastic Surgery', 'Lower Extremity Plastic Surgery'), ('Massage Therapist', 'Massage Therapist'), ('Medical Genetics', 'Medical Genetics'), ('Medical Technology', 'Medical Technology'), ('Neurological Plastic Surgery', 'Neurological Plastic Surgery'), ('Neurology', 'Neurology'), ('Nuclear Medicine', 'Nuclear Medicine'), ('Nutrition and Dietetics', 'Nutrition and Dietetics'), ('Nutrition Consultant', 'Nutrition Consultant'), ('Obstetrics and Gynecology', 'Obstetrics and Gynecology'), ('Oncologic Plastic Surgery', 'Oncologic Plastic Surgery'), ('Ophthalmology', 'Ophthalmology'), ('Pathology', 'Pathology'), ('Pediatrics', 'Pediatrics'), ('Pediatric Cardiovascular Surgery', 'Pediatric Cardiovascular Surgery'), ('Pediatric Endocrinology', 'Pediatric Endocrinology'), ('Pediatric Gastroenterology', 'Pediatric Gastroenterology'), ('Pediatric General Surgery', 'Pediatric General Surgery'), ('Pediatric Hematology', 'Pediatric Hematology'), ('Pediatric Infectious Disease', 'Pediatric Infectious Disease'), ('Pediatric Nephrology', 'Pediatric Nephrology'), ('Pediatric Neurosurgery', 'Pediatric Neurosurgery'), ('Pediatric Oncology', 'Pediatric Oncology'), ('Pediatric Orthopedics', 'Pediatric Orthopedics'), ('Pediatric Otolaryngology', 'Pediatric Otolaryngology'), ('Pediatric Plastic Surgery', 'Pediatric Plastic Surgery'), ('Pediatric Pulmonology', 'Pediatric Pulmonology'), ('Pediatric Rheumatology', 'Pediatric Rheumatology'), ('Physical Medicine and Rehabilitation', 'Physical Medicine and Rehabilitation'), ('Plastic Surgery', 'Plastic Surgery'), ('Preventive Medicine', 'Preventive Medicine'), ('Psychiatry', 'Psychiatry'), ('Radiation Oncology', 'Radiation Oncology'), ('Reconstructive Plastic Surgery', 'Reconstructive Plastic Surgery'), ('Respiratory Plastic Surgery', 'Respiratory Plastic Surgery'), ('Surgery', 'Surgery'), ('Thoracic Surgery', 'Thoracic Surgery'), ('Upper Extremity Plastic Surgery', 'Upper Extremity Plastic Surgery'), ('Urogenital Plastic Surgery', 'Urogenital Plastic Surgery'), ('Urology', 'Urology'), ('Vascular Surgery', 'Vascular Surgery'), ('Yoga and Mindfulness Specialist', 'Yoga and Mindfulness Specialist')], max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='MedicalTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام آزمایش پزشکی')),
                ('test_date', models.DateTimeField(verbose_name='تاریخ آزمایش')),
                ('result', models.CharField(max_length=100, verbose_name='نتیجه آزمایش')),
                ('reference_range', models.CharField(max_length=100, verbose_name='محدوده مرجع')),
                ('interpretation', models.TextField(verbose_name='تفسیر نتیجه آزمایش')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.medical_technology_patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalImaging',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام تصویربرداری پزشکی')),
                ('imaging_date', models.DateTimeField(verbose_name='تاریخ تصویربرداری')),
                ('description', models.TextField(verbose_name='توضیحات تصویربرداری')),
                ('image_file', models.ImageField(upload_to='medical_imaging/', verbose_name='فایل تصویر')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.medical_technology_patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
