# Generated by Django 4.2.3 on 2023-08-26 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0024_medical_technology_patient_medicaldevice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTechnologyMedicalAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('action_date', models.DateField()),
                ('action_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='medical_technology_Treatment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('treatment_date', models.DateTimeField(verbose_name='تاریخ درمان')),
                ('treatment_description', models.TextField(verbose_name='توضیحات درمان')),
                ('medical_devices', models.ManyToManyField(blank=True, to='treatment.medicaldevice', verbose_name='دستگاه\u200cهای مرتبط')),
                ('medical_imagings', models.ManyToManyField(blank=True, to='treatment.medicalimaging', verbose_name='تصویربرداری\u200cهای مرتبط')),
                ('medical_tests', models.ManyToManyField(blank=True, to='treatment.medicaltest', verbose_name='آزمایش\u200cهای مرتبط')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='treatment.medical_technology_patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
