# Generated by Django 4.2.3 on 2023-08-27 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_remove_user_group_delete_groupsuser'),
        ('treatment', '0027_aerospace_medicine_patient_spacemission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='nose_job_Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nose_job_Patient', to='common.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoseJobSurgery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('surgery_date', models.DateField(verbose_name='تاریخ جراحی Nose Job')),
                ('surgery_notes', models.TextField(verbose_name='یادداشت\u200cهای جراحی Nose Job')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nose_job_surgeries', to='treatment.nose_job_patient')),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_nose_job_surgeries', to='common.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoseJobRecovery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('recovery_start_date', models.DateField(verbose_name='تاریخ شروع بازیابی Nose Job')),
                ('recovery_end_date', models.DateField(verbose_name='تاریخ پایان بازیابی Nose Job')),
                ('recovery_notes', models.TextField(verbose_name='یادداشت\u200cهای بازیابی Nose Job')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nose_job_recoveries', to='treatment.nose_job_patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoseJobPostTreatment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('post_treatment_date', models.DateField(verbose_name='تاریخ اقدامات پس از درمان Nose Job')),
                ('post_treatment_notes', models.TextField(verbose_name='یادداشت\u200cهای اقدامات پس از درمان Nose Job')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nose_job_post_treatments', to='treatment.nose_job_patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoseJobParaclinicalExam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('exam_date', models.DateField(verbose_name='تاریخ آزمون پاراکلینیکی Nose Job')),
                ('exam_notes', models.TextField(verbose_name='یادداشت\u200cهای آزمون پاراکلینیکی Nose Job')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nose_job_paraclinical_exams', to='treatment.nose_job_patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoseJobNursing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('nursing_date', models.DateField(verbose_name='تاریخ پرستاری Nose Job')),
                ('nursing_notes', models.TextField(verbose_name='یادداشت\u200cهای پرستاری Nose Job')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nose_job_nursing', to='treatment.nose_job_patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoseJobHospitalization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('hospitalization_date', models.DateField(verbose_name='تاریخ بستری Nose Job')),
                ('hospitalization_notes', models.TextField(verbose_name='یادداشت\u200cهای بستری Nose Job')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nose_job_hospitalizations', to='treatment.nose_job_patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoseJobConsultation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('consultation_date', models.DateField(verbose_name='تاریخ مشاوره Nose Job')),
                ('consultation_notes', models.TextField(verbose_name='یادداشت\u200cهای مشاوره Nose Job')),
                ('consulting_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulted_nose_job_patients', to='common.person')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nose_job_consultations', to='treatment.nose_job_patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoseJobClinicalStage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('stage_date', models.DateField(verbose_name='تاریخ مرحله کلینیکی Nose Job')),
                ('clinical_notes', models.TextField(verbose_name='یادداشت\u200cهای مرحله کلینیکی Nose Job')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nose_job_clinical_stages', to='treatment.nose_job_patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
