# Generated by Django 4.2.3 on 2023-08-27 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_remove_user_group_delete_groupsuser'),
        ('treatment', '0028_nose_job_patient_nosejobsurgery_nosejobrecovery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CosmeticDermatologyPatient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cosmetic_dermatology_patients', to='common.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CosmeticProcedure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام روش درمانی')),
                ('description', models.TextField(verbose_name='توضیحات روش درمانی')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CosmeticProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('description', models.TextField(verbose_name='توضیحات محصول')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت محصول')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CosmeticSkinTreatment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('visit_date', models.DateTimeField(verbose_name='تاریخ ویزیت')),
                ('symptoms', models.TextField(verbose_name='علائم و مشکلات پوست')),
                ('diagnosis', models.TextField(verbose_name='تشخیص پوستی')),
                ('recommendations', models.TextField(verbose_name='توصیه\u200cهای پس از درمان')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.cosmeticdermatologypatient', verbose_name='بیمار')),
                ('treatments', models.ManyToManyField(blank=True, to='treatment.cosmeticskintreatment', verbose_name='روش\u200cهای درمانی زیبایی پوست')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CosmeticTreatmentPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('treatment_date', models.DateTimeField(verbose_name='تاریخ برنامه\u200cریزی درمان')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosmetic_plans', to='treatment.dermatology_patient', verbose_name='بیمار')),
                ('procedures', models.ManyToManyField(to='treatment.cosmeticprocedure', verbose_name='روش\u200cهای درمانی')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CosmeticTreatmentImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('image', models.ImageField(upload_to='cosmetic_treatment_images/', verbose_name='تصویر')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='treatment.cosmeticskintreatment', verbose_name='روش درمانی')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CosmeticProcedureOutcome',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('outcome_description', models.TextField(verbose_name='توضیحات نتیجه')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='treatment.cosmeticprocedure', verbose_name='روش درمانی')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CosmeticProcedureImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('image', models.ImageField(upload_to='cosmetic_procedure_images/', verbose_name='تصویر')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='treatment.cosmeticprocedure', verbose_name='روش درمانی')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CosmeticPatientReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('review_text', models.TextField(verbose_name='متن نظر')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosmetic_reviews', to='treatment.dermatology_patient', verbose_name='بیمار')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.cosmeticprocedure', verbose_name='روش درمانی')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CosmeticPatientFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('feedback_text', models.TextField(verbose_name='متن بازخورد')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosmetic_feedback', to='treatment.dermatology_patient', verbose_name='بیمار')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.cosmeticprocedure', verbose_name='روش درمانی')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
