# Generated by Django 4.2.3 on 2023-08-27 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_remove_user_group_delete_groupsuser'),
        ('treatment', '0029_cosmeticdermatologypatient_cosmeticprocedure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceliftProcedure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام روش درمانی')),
                ('description', models.TextField(verbose_name='توضیحات روش درمانی')),
                ('duration', models.DurationField(verbose_name='مدت زمان انجام درمان')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='هزینه درمان')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowUpVisit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('visit_date', models.DateTimeField(verbose_name='تاریخ ویزیت پس از درمان')),
                ('notes', models.TextField(verbose_name='یادداشت\u200cهای ویزیت پس از درمان')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostTreatmentInstructions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('instructions', models.TextField(verbose_name='دستورات پس از درمان')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreTreatmentChecklist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('checklist_items', models.TextField(verbose_name='موارد بررسی قبل از درمان')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacialPlasticSurgeryPatient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facial_plastic_surgery_patients', to='common.person')),
            ],
            options={
                'db_table': 'facial_plastic_surgery_patient',
            },
        ),
        migrations.CreateModel(
            name='FaceliftTreatment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('treatment_date', models.DateTimeField(verbose_name='تاریخ درمان')),
                ('treatment_notes', models.TextField(verbose_name='یادداشت\u200cهای درمان')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.facialplasticsurgerypatient', verbose_name='بیمار')),
                ('pre_treatment_checklist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treatment.pretreatmentchecklist', verbose_name='لیست بررسی قبل از درمان')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treatment.faceliftprocedure', verbose_name='روش درمانی')),
            ],
            options={
                'db_table': 'facelift_treatment',
            },
        ),
    ]
