# Generated by Django 4.2.3 on 2023-08-27 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0030_faceliftprocedure_followupvisit_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowUpVisit',
            new_name='FaceliftFollowUpVisit',
        ),
    ]
