# Generated by Django 4.2.3 on 2023-08-27 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_remove_user_group_delete_groupsuser'),
        ('treatment', '0031_rename_followupvisit_faceliftfollowupvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlepharoplastyBeforeAndAfterPhotos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('before_photo', models.ImageField(upload_to='blepharoplasty_photos', verbose_name='تصویر قبل از درمان')),
                ('after_photo', models.ImageField(upload_to='blepharoplasty_photos', verbose_name='تصویر بعد از درمان')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlepharoplastyPatient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blepharoplasty_patients', to='common.person')),
            ],
            options={
                'db_table': 'blepharoplasty_patient',
            },
        ),
    ]
