# Generated by Django 4.2.3 on 2023-08-27 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0032_blepharoplastybeforeandafterphotos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlepharoplastyDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تشخیص')),
                ('description', models.TextField(verbose_name='توضیحات تشخیص')),
            ],
        ),
        migrations.CreateModel(
            name='BlepharoplastyOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_description', models.TextField(verbose_name='توضیحات نتیجه درمان')),
                ('prognosis', models.TextField(verbose_name='پیش\u200cبینی پس از درمان')),
            ],
        ),
        migrations.CreateModel(
            name='BlepharoplastyPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=100, verbose_name='نام دارو')),
                ('dosage', models.CharField(max_length=50, verbose_name='مقدار دوز دارو')),
                ('usage_instructions', models.TextField(verbose_name='دستورات مصرف دارو')),
            ],
        ),
        migrations.CreateModel(
            name='BlepharoplastySymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام علامت')),
                ('description', models.TextField(verbose_name='توضیحات علامت')),
            ],
        ),
        migrations.CreateModel(
            name='BlepharoplastyTreatment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('treatment_date', models.DateTimeField(verbose_name='تاریخ درمان')),
                ('treatment_description', models.TextField(verbose_name='توضیحات درمان')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='treatment.blepharoplastypatient')),
            ],
            options={
                'db_table': 'blepharoplasty_treatment',
            },
        ),
        migrations.CreateModel(
            name='BlepharoplastyVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(verbose_name='تاریخ ویزیت')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treatment.blepharoplastydiagnosis', verbose_name='تشخیص')),
                ('outcomes', models.ManyToManyField(blank=True, to='treatment.blepharoplastyoutcome', verbose_name='نتایج درمان')),
                ('prescriptions', models.ManyToManyField(blank=True, to='treatment.blepharoplastyprescription', verbose_name='نسخه\u200cهای دارویی')),
                ('symptoms', models.ManyToManyField(blank=True, to='treatment.blepharoplastysymptom', verbose_name='علائم')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='treatment.blepharoplastytreatment')),
            ],
        ),
        migrations.CreateModel(
            name='BlepharoplastyProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_date', models.DateTimeField(verbose_name='تاریخ مرحله درمانی')),
                ('procedure_description', models.TextField(verbose_name='توضیحات مرحله درمانی')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='treatment.blepharoplastytreatment')),
            ],
            options={
                'db_table': 'blepharoplasty_procedure',
            },
        ),
        migrations.AddField(
            model_name='blepharoplastyprescription',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='treatment.blepharoplastytreatment'),
        ),
        migrations.CreateModel(
            name='BlepharoplastyMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=100, verbose_name='نام دارو')),
                ('dosage', models.CharField(max_length=50, verbose_name='مقدار دوز دارو')),
                ('usage_instructions', models.TextField(verbose_name='دستورات مصرف دارو')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='treatment.blepharoplastytreatment')),
            ],
        ),
    ]
