# Generated by Django 4.2.3 on 2023-08-27 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_remove_user_group_delete_groupsuser'),
        ('treatment', '0034_blepharoplastydiagnosis_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanthoplastyEyeCondition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام بیماری چشمی')),
                ('description', models.TextField(verbose_name='توضیحات بیماری چشمی')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CanthoplastyPatient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='canthoplasty_patients', to='common.person')),
            ],
            options={
                'db_table': 'canthoplasty_patient',
            },
        ),
        migrations.CreateModel(
            name='CanthoplastyPrescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('medication', models.CharField(max_length=100, verbose_name='نام دارو')),
                ('dosage', models.CharField(max_length=50, verbose_name='مقدار دوز دارو')),
                ('usage_instructions', models.TextField(verbose_name='دستورات مصرف دارو')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CanthoplastyTreatment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('treatment_date', models.DateTimeField(verbose_name='تاریخ درمان')),
                ('symptoms', models.TextField(verbose_name='علائم بیماری')),
                ('diagnosis', models.TextField(verbose_name='تشخیص بیماری')),
                ('eye_conditions', models.ManyToManyField(blank=True, to='treatment.canthoplastyeyecondition', verbose_name='بیماری\u200cهای چشمی')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='treatment.canthoplastypatient')),
                ('prescriptions', models.ManyToManyField(blank=True, to='treatment.canthoplastyprescription', verbose_name='نسخه\u200cهای دارویی')),
            ],
            options={
                'db_table': 'canthoplasty_treatment',
            },
        ),
        migrations.CreateModel(
            name='CanthoplastyProcedure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('procedure_date', models.DateTimeField(verbose_name='تاریخ مرحله درمانی')),
                ('procedure_description', models.TextField(verbose_name='توضیحات مرحله درمانی')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='treatment.canthoplastytreatment')),
            ],
            options={
                'db_table': 'canthoplasty_procedure',
            },
        ),
    ]
