# Generated by Django 4.2.3 on 2023-08-27 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_remove_user_group_delete_groupsuser'),
        ('treatment', '0035_canthoplastyeyecondition_canthoplastypatient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtoplastyPatient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='otoplasty_patients', to='common.person')),
            ],
            options={
                'db_table': 'otoplasty_patient',
            },
        ),
        migrations.CreateModel(
            name='OtoplastyTreatment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('treatment_date', models.DateTimeField(verbose_name='تاریخ شروع درمان')),
                ('treatment_description', models.TextField(verbose_name='توضیحات درمان')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='treatment.otoplastypatient', verbose_name='بیمار')),
            ],
            options={
                'db_table': 'otoplasty_treatment',
            },
        ),
        migrations.CreateModel(
            name='OtoplastyVisit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('visit_date', models.DateTimeField(verbose_name='تاریخ ویزیت')),
                ('visit_description', models.TextField(verbose_name='توضیحات ویزیت')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='treatment.otoplastytreatment')),
            ],
            options={
                'db_table': 'otoplasty_visit',
            },
        ),
        migrations.CreateModel(
            name='OtoplastyProcedure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('procedure_date', models.DateTimeField(verbose_name='تاریخ مرحله درمانی')),
                ('procedure_description', models.TextField(verbose_name='توضیحات مرحله درمانی')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='treatment.otoplastytreatment')),
            ],
            options={
                'db_table': 'otoplasty_procedure',
            },
        ),
        migrations.CreateModel(
            name='OtoplastyMedication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('medication', models.CharField(max_length=100, verbose_name='نام دارو')),
                ('dosage', models.CharField(max_length=50, verbose_name='مقدار دوز دارو')),
                ('usage_instructions', models.TextField(verbose_name='دستورات مصرف دارو')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='treatment.otoplastytreatment')),
            ],
            options={
                'db_table': 'otoplasty_medication',
            },
        ),
        migrations.CreateModel(
            name='OtoplastyDiagnosis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('diagnosis_date', models.DateTimeField(verbose_name='تاریخ تشخیص')),
                ('diagnosis_description', models.TextField(verbose_name='توضیحات تشخیص')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='treatment.otoplastytreatment')),
            ],
            options={
                'db_table': 'otoplasty_diagnosis',
            },
        ),
    ]
