# Generated by Django 4.2.3 on 2023-08-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0036_otoplastypatient_otoplastytreatment_otoplastyvisit_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OtoplastyDiagnosis',
            new_name='OtoplastyDiagnosiss',
        ),
    ]
