# Generated by Django 4.2.3 on 2023-08-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0037_rename_otoplastydiagnosis_otoplastydiagnosiss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OtoplastyDiagnosiss',
            new_name='OtoplastyDiagnosis',
        ),
    ]
