# Generated by Django 4.2.3 on 2023-08-27 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_remove_user_group_delete_groupsuser'),
        ('treatment', '0038_rename_otoplastydiagnosiss_otoplastydiagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuccalFatRemovalDiagnosis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام تشخیص')),
                ('description', models.TextField(verbose_name='توضیحات تشخیص')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuccalFatRemovalPatient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buccal_fat_removal_patients', to='common.person')),
            ],
            options={
                'db_table': 'buccal_fat_removal_patient',
            },
        ),
        migrations.CreateModel(
            name='BuccalFatRemovalTreatment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('treatment_date', models.DateTimeField(verbose_name='تاریخ درمان')),
                ('diagnosis', models.ManyToManyField(blank=True, to='treatment.buccalfatremovaldiagnosis', verbose_name='تشخیص\u200cها')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.buccalfatremovalpatient', verbose_name='بیمار')),
            ],
            options={
                'db_table': 'buccal_fat_removal_treatment',
            },
        ),
        migrations.CreateModel(
            name='BuccalFatRemovalProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_date', models.DateTimeField(verbose_name='تاریخ مرحله درمانی')),
                ('procedure_description', models.TextField(verbose_name='توضیحات مرحله درمانی')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='treatment.buccalfatremovaltreatment')),
            ],
            options={
                'db_table': 'buccal_fat_removal_procedure',
            },
        ),
    ]
