# Generated by Django 4.2.3 on 2023-08-27 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_remove_user_group_delete_groupsuser'),
        ('treatment', '0040_threadliftdiagnosis_threadliftpatient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DermalFillerPatient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dermal_filler_patients', to='common.person')),
            ],
            options={
                'db_table': 'dermal_filler_patient',
            },
        ),
        migrations.CreateModel(
            name='DermalFillerProcedure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('procedure_date', models.DateTimeField(verbose_name='تاریخ مرحله درمانی')),
                ('procedure_description', models.TextField(verbose_name='توضیحات مرحله درمانی')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='treatment.dermalfillerpatient')),
            ],
            options={
                'db_table': 'dermal_filler_procedure',
            },
        ),
        migrations.CreateModel(
            name='DermalFillerPrescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('medication', models.CharField(max_length=100, verbose_name='نام دارو')),
                ('dosage', models.CharField(max_length=50, verbose_name='مقدار دوز دارو')),
                ('usage_instructions', models.TextField(verbose_name='دستورات مصرف دارو')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='treatment.dermalfillerprocedure')),
            ],
            options={
                'db_table': 'dermal_filler_prescription',
            },
        ),
        migrations.CreateModel(
            name='DermalFillerFollowUp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('followup_date', models.DateTimeField(verbose_name='تاریخ پیگیری')),
                ('followup_description', models.TextField(verbose_name='توضیحات پیگیری')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='treatment.dermalfillerprocedure')),
            ],
            options={
                'db_table': 'dermal_filler_followup',
            },
        ),
        migrations.CreateModel(
            name='DermalFillerDiagnosis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('diagnosis_date', models.DateTimeField(verbose_name='تاریخ تشخیص')),
                ('diagnosis_description', models.TextField(verbose_name='توضیحات تشخیص')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='treatment.dermalfillerprocedure')),
            ],
            options={
                'db_table': 'dermal_filler_diagnosis',
            },
        ),
    ]
