# Generated by Django 4.2.3 on 2023-08-27 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0041_dermalfillerpatient_dermalfillerprocedure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DermalFillerVisit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('visit_date', models.DateTimeField(verbose_name='تاریخ ویزیت')),
                ('visit_description', models.TextField(verbose_name='توضیحات ویزیت')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='treatment.dermalfillerprocedure')),
            ],
            options={
                'db_table': 'dermal_filler_visit',
            },
        ),
        migrations.CreateModel(
            name='DermalFillerTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('test_date', models.DateTimeField(verbose_name='تاریخ آزمایش')),
                ('test_description', models.TextField(verbose_name='توضیحات آزمایش')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='treatment.dermalfillerprocedure')),
            ],
            options={
                'db_table': 'dermal_filler_test',
            },
        ),
    ]
