# Generated by Django 4.2.3 on 2023-08-27 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0042_dermalfillervisit_dermalfillertest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DermalFillerTreatment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('treatment_date', models.DateTimeField(verbose_name='تاریخ درمان')),
                ('treatment_description', models.TextField(verbose_name='توضیحات درمان')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dermal_filler_treatments', to='treatment.dermalfillerpatient')),
                ('prescriptions', models.ManyToManyField(blank=True, to='treatment.dermalfillerprescription', verbose_name='نسخه\u200cهای دارویی')),
                ('tests', models.ManyToManyField(blank=True, to='treatment.dermalfillertest', verbose_name='آزمایش\u200cها')),
                ('visits', models.ManyToManyField(blank=True, to='treatment.dermalfillervisit', verbose_name='ویزیت\u200cها')),
            ],
            options={
                'db_table': 'dermal_filler_treatment',
            },
        ),
    ]
