# Generated by Django 4.2.3 on 2023-08-27 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_remove_user_group_delete_groupsuser'),
        ('treatment', '0043_dermalfillertreatment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltherapyDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تشخیص')),
                ('description', models.TextField(verbose_name='توضیحات تشخیص')),
            ],
        ),
        migrations.CreateModel(
            name='UltherapyPatient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ultherapy_patients', to='common.person')),
            ],
            options={
                'db_table': 'ultherapy_patient',
            },
        ),
        migrations.CreateModel(
            name='UltherapyPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=100, verbose_name='نام دارو')),
                ('dosage', models.CharField(max_length=50, verbose_name='مقدار دوز دارو')),
                ('usage_instructions', models.TextField(verbose_name='دستورات مصرف دارو')),
            ],
        ),
        migrations.CreateModel(
            name='UltherapyTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(verbose_name='تاریخ ویزیت')),
                ('diagnosis', models.ManyToManyField(blank=True, to='treatment.ultherapydiagnosis', verbose_name='تشخیص\u200cها')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='treatment.ultherapypatient')),
                ('prescriptions', models.ManyToManyField(blank=True, to='treatment.ultherapyprescription', verbose_name='نسخه\u200cهای دارویی')),
            ],
        ),
        migrations.CreateModel(
            name='UltherapyProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_date', models.DateTimeField(verbose_name='تاریخ مرحله درمانی')),
                ('procedure_description', models.TextField(verbose_name='توضیحات مرحله درمانی')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='treatment.ultherapytreatment')),
            ],
        ),
    ]
