# Generated by Django 4.2.3 on 2023-08-27 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0045_dentalcondition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalProcedure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام روش درمانی دندانی')),
                ('description', models.TextField(verbose_name='توضیحات روش درمانی دندانی')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='dentistry_and_oral_aesthetics_Prescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('medication', models.CharField(max_length=100, verbose_name='نام دارو')),
                ('dosage', models.CharField(max_length=50, verbose_name='مقدار دوز دارو')),
                ('usage_instructions', models.TextField(verbose_name='دستورات مصرف دارو')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DentalTreatment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('treatment_date', models.DateTimeField(verbose_name='تاریخ درمان دندانی')),
                ('symptoms', models.TextField(verbose_name='علائم بیماری دندانی')),
                ('diagnosis', models.TextField(verbose_name='تشخیص بیماری دندانی')),
                ('dental_conditions', models.ManyToManyField(blank=True, to='treatment.dentalcondition', verbose_name='بیماری\u200cهای دندانی')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.dentistry_and_oral_aesthetics_patient', verbose_name='بیمار')),
                ('prescriptions', models.ManyToManyField(blank=True, to='treatment.dentistry_and_oral_aesthetics_prescription', verbose_name='نسخه\u200cهای دارویی')),
                ('procedures', models.ManyToManyField(blank=True, to='treatment.dentalprocedure', verbose_name='روش\u200cهای درمانی دندانی')),
            ],
            options={
                'db_table': 'dentistry_and_oral_aesthetics_Treatment',
            },
        ),
    ]
