# Generated by Django 4.2.3 on 2023-08-27 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_remove_user_group_delete_groupsuser'),
        ('treatment', '0046_dentalprocedure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HIFU_DentistryPatient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='HIFU_DentistryPatient', to='common.person')),
            ],
            options={
                'db_table': 'HIFU_DentistryPatient',
            },
        ),
        migrations.CreateModel(
            name='HIFUTreatment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('treatment_date', models.DateTimeField(verbose_name='تاریخ درمان HIFU')),
                ('symptoms', models.TextField(verbose_name='علائم بیماری')),
                ('diagnosis', models.TextField(verbose_name='تشخیص بیماری')),
                ('procedure_description', models.TextField(verbose_name='توضیحات روش درمانی HIFU')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.hifu_dentistrypatient', verbose_name='بیمار')),
            ],
            options={
                'db_table': 'HIFU_Treatment',
            },
        ),
    ]
