# Generated by Django 4.2.3 on 2023-08-27 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0047_hifu_dentistrypatient_hifutreatment'),
    ]

    operations = [
        migrations.CreateModel(
            name='HIFUTreatmentAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('action_date', models.DateTimeField(verbose_name='تاریخ اقدام درمانی')),
                ('action_description', models.TextField(verbose_name='توضیحات اقدام درمانی')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.hifu_dentistrypatient', verbose_name='بیمار')),
            ],
            options={
                'db_table': 'TreatmentAction',
            },
        ),
        migrations.CreateModel(
            name='HIFUPreTreatmentAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('action_date', models.DateTimeField(verbose_name='تاریخ اقدام پیش از درمان')),
                ('action_description', models.TextField(verbose_name='توضیحات اقدام پیش از درمان')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.hifu_dentistrypatient', verbose_name='بیمار')),
            ],
            options={
                'db_table': 'PreTreatmentAction',
            },
        ),
        migrations.CreateModel(
            name='HIFUMedicalTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('test_date', models.DateTimeField(verbose_name='تاریخ آزمایش پزشکی')),
                ('test_name', models.CharField(max_length=100, verbose_name='نام آزمایش')),
                ('test_result', models.TextField(verbose_name='نتایج آزمایش')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.hifu_dentistrypatient', verbose_name='بیمار')),
            ],
            options={
                'db_table': 'MedicalTest',
            },
        ),
        migrations.CreateModel(
            name='HIFUMedicalPrescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('prescription_date', models.DateTimeField(verbose_name='تاریخ تجویز دارو')),
                ('medication', models.CharField(max_length=100, verbose_name='نام دارو')),
                ('dosage', models.CharField(max_length=50, verbose_name='مقدار دوز دارو')),
                ('usage_instructions', models.TextField(verbose_name='دستورات مصرف دارو')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.hifu_dentistrypatient', verbose_name='بیمار')),
            ],
            options={
                'db_table': 'MedicalPrescription',
            },
        ),
        migrations.CreateModel(
            name='HIFUMedicalImaging',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('imaging_date', models.DateTimeField(verbose_name='تاریخ عکس\u200cبرداری پزشکی')),
                ('imaging_type', models.CharField(max_length=100, verbose_name='نوع عکس\u200cبرداری')),
                ('imaging_result', models.TextField(verbose_name='نتایج عکس\u200cبرداری')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.hifu_dentistrypatient', verbose_name='بیمار')),
            ],
            options={
                'db_table': 'MedicalImaging',
            },
        ),
        migrations.CreateModel(
            name='HIFUMedicalDiagnosis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('diagnosis_date', models.DateTimeField(verbose_name='تاریخ تشخیص پزشکی')),
                ('diagnosis_description', models.TextField(verbose_name='توضیحات تشخیص پزشکی')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.hifu_dentistrypatient', verbose_name='بیمار')),
            ],
            options={
                'db_table': 'MedicalDiagnosis',
            },
        ),
        migrations.CreateModel(
            name='HIFUFollowUp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('follow_up_date', models.DateTimeField(verbose_name='تاریخ پیگیری بعد از درمان')),
                ('follow_up_notes', models.TextField(verbose_name='یادداشت\u200cهای پیگیری بعد از درمان')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='treatment.hifutreatment', verbose_name='روند درمان HIFU')),
            ],
            options={
                'db_table': 'HIFU_FollowUp',
            },
        ),
    ]
