# Generated by Django 4.2.3 on 2023-08-27 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_remove_user_group_delete_groupsuser'),
        ('treatment', '0048_hifutreatmentaction_hifupretreatmentaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DermatologyTreatment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('visit_date', models.DateTimeField(verbose_name='تاریخ ویزیت')),
                ('symptoms', models.TextField(verbose_name='علائم بیماری')),
                ('diagnosis', models.TextField(verbose_name='تشخیص بیماری')),
            ],
            options={
                'db_table': 'dermatology_treatment',
            },
        ),
        migrations.CreateModel(
            name='HIFUDermatologyPatient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dermatology_patients', to='common.person')),
            ],
            options={
                'db_table': 'dermatology_patient',
            },
        ),
        migrations.CreateModel(
            name='HIFUPrescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('medication', models.CharField(max_length=100, verbose_name='نام دارو')),
                ('dosage', models.CharField(max_length=50, verbose_name='مقدار دوز دارو')),
                ('usage_instructions', models.TextField(verbose_name='دستورات مصرف دارو')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HIFUSkinCondition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام بیماری')),
                ('description', models.TextField(verbose_name='توضیحات بیماری')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='hifufollowup',
            name='treatment',
        ),
        migrations.RemoveField(
            model_name='hifumedicaldiagnosis',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='hifumedicalimaging',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='hifumedicalprescription',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='hifumedicaltest',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='hifupretreatmentaction',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='hifutreatment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='hifutreatmentaction',
            name='patient',
        ),
        migrations.DeleteModel(
            name='HIFU_DentistryPatient',
        ),
        migrations.DeleteModel(
            name='HIFUFollowUp',
        ),
        migrations.DeleteModel(
            name='HIFUMedicalDiagnosis',
        ),
        migrations.DeleteModel(
            name='HIFUMedicalImaging',
        ),
        migrations.DeleteModel(
            name='HIFUMedicalPrescription',
        ),
        migrations.DeleteModel(
            name='HIFUMedicalTest',
        ),
        migrations.DeleteModel(
            name='HIFUPreTreatmentAction',
        ),
        migrations.DeleteModel(
            name='HIFUTreatment',
        ),
        migrations.DeleteModel(
            name='HIFUTreatmentAction',
        ),
        migrations.AddField(
            model_name='dermatologytreatment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.hifudermatologypatient', verbose_name='بیمار'),
        ),
        migrations.AddField(
            model_name='dermatologytreatment',
            name='prescriptions',
            field=models.ManyToManyField(blank=True, to='treatment.prescription', verbose_name='نسخه\u200cهای دارویی'),
        ),
        migrations.AddField(
            model_name='dermatologytreatment',
            name='skin_conditions',
            field=models.ManyToManyField(blank=True, to='treatment.skincondition', verbose_name='بیماری\u200cهای پوستی'),
        ),
    ]
