# Generated by Django 4.2.3 on 2023-08-27 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_remove_user_group_delete_groupsuser'),
        ('treatment', '0049_dermatologytreatment_hifudermatologypatient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalPeelDermatologyPatient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chemicalpeel_dermatology_patients', to='common.person')),
            ],
            options={
                'db_table': 'ChemicalPeeldermatology_patient',
            },
        ),
        migrations.CreateModel(
            name='ChemicalPeelPrescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('medication', models.CharField(max_length=100, verbose_name='نام دارو')),
                ('dosage', models.CharField(max_length=50, verbose_name='مقدار دوز دارو')),
                ('usage_instructions', models.TextField(verbose_name='دستورات مصرف دارو')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChemicalPeelSkinCondition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام بیماری')),
                ('description', models.TextField(verbose_name='توضیحات بیماری')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelTable(
            name='dermatologytreatment',
            table='HIFUdermatology_treatment',
        ),
        migrations.AlterModelTable(
            name='hifudermatologypatient',
            table='HIFUdermatology_patient',
        ),
        migrations.CreateModel(
            name='ChemicalPeelDermatologyTreatment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('visit_date', models.DateTimeField(verbose_name='تاریخ ویزیت')),
                ('symptoms', models.TextField(verbose_name='علائم بیماری')),
                ('diagnosis', models.TextField(verbose_name='تشخیص بیماری')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.chemicalpeeldermatologypatient', verbose_name='بیمار')),
                ('prescriptions', models.ManyToManyField(blank=True, to='treatment.prescription', verbose_name='نسخه\u200cهای دارویی')),
                ('skin_conditions', models.ManyToManyField(blank=True, to='treatment.skincondition', verbose_name='بیماری\u200cهای پوستی')),
            ],
            options={
                'db_table': 'ChemicalPeeldermatology_treatment',
            },
        ),
        migrations.CreateModel(
            name='ChemicalPeelChemicalPeelTreatment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('visit_date', models.DateTimeField(verbose_name='تاریخ ویزیت')),
                ('symptoms', models.TextField(verbose_name='علائم بیماری')),
                ('diagnosis', models.TextField(verbose_name='تشخیص بیماری')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.chemicalpeeldermatologypatient', verbose_name='بیمار')),
                ('prescriptions', models.ManyToManyField(blank=True, to='treatment.prescription', verbose_name='نسخه\u200cهای دارویی')),
                ('skin_conditions', models.ManyToManyField(blank=True, to='treatment.skincondition', verbose_name='بیماری\u200cهای پوستی')),
            ],
            options={
                'db_table': 'chemical_peel_treatment',
            },
        ),
    ]
