# Generated by Django 4.2.3 on 2023-08-27 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_remove_user_group_delete_groupsuser'),
        ('treatment', '0050_chemicalpeeldermatologypatient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mommyMakeover_Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mommyMakeover_Patient', to='common.person')),
            ],
            options={
                'db_table': 'mommyMakeover_Patient',
            },
        ),
        migrations.CreateModel(
            name='mommyMakeover_Surgery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('surgery_date', models.DateField(verbose_name='تاریخ جراحی')),
                ('surgical_procedure', models.TextField(verbose_name='روش\u200cهای جراحی')),
                ('complications', models.TextField(blank=True, verbose_name='مشکلات و عوارض')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.mommymakeover_patient', verbose_name='بیمار')),
            ],
            options={
                'db_table': 'mommyMakeover_Surgery',
            },
        ),
        migrations.CreateModel(
            name='mommyMakeover_Recovery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('recovery_start_date', models.DateField(verbose_name='تاریخ شروع بازیابی')),
                ('recovery_description', models.TextField(verbose_name='توضیحات فرآیند بازیابی')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.mommymakeover_patient', verbose_name='بیمار')),
            ],
            options={
                'db_table': 'mommyMakeover_Recovery',
            },
        ),
    ]
