# Generated by Django 4.2.3 on 2023-08-27 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_remove_user_group_delete_groupsuser'),
        ('treatment', '0051_mommymakeover_patient_mommymakeover_surgery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowerBodyLiftComplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام عارضه')),
                ('description', models.TextField(verbose_name='توضیحات عارضه')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LowerBodyLiftPatient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lower_body_lift_patients', to='common.person')),
            ],
            options={
                'db_table': 'LowerBodyLift_Patient',
            },
        ),
        migrations.CreateModel(
            name='LowerBodyLiftSurgicalProcedure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('procedure_date', models.DateTimeField(verbose_name='تاریخ عمل جراحی')),
                ('surgical_team', models.TextField(verbose_name='تیم جراحی')),
                ('incision_sites', models.TextField(verbose_name='محل برش\u200cها')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.lowerbodyliftpatient', verbose_name='بیمار')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LowerBodyLiftPreoperativeAssessment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('assessment_date', models.DateTimeField(verbose_name='تاریخ ارزیابی')),
                ('medical_history', models.TextField(verbose_name='سوابق پزشکی بیمار')),
                ('physical_exam', models.TextField(verbose_name='معاینه فیزیکی')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.lowerbodyliftpatient', verbose_name='بیمار')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LowerBodyLiftPostoperativeCare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('care_date', models.DateTimeField(verbose_name='تاریخ مراقبت بعد از جراحی')),
                ('care_instructions', models.TextField(verbose_name='دستورات مراقبت')),
                ('complications', models.ManyToManyField(blank=True, to='treatment.lowerbodyliftcomplication', verbose_name='عوارض')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.lowerbodyliftpatient', verbose_name='بیمار')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
