# Generated by Django 4.2.3 on 2023-08-28 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0052_lowerbodyliftcomplication_lowerbodyliftpatient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpperBodyLiftPatient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('full_name', models.CharField(max_length=100, verbose_name='نام کامل بیمار')),
                ('age', models.PositiveIntegerField(verbose_name='سن بیمار')),
            ],
            options={
                'db_table': 'upper_body_lift_patient',
            },
        ),
        migrations.CreateModel(
            name='UpperBodyLiftSurgicalProcedure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('date', models.DateField(verbose_name='تاریخ جراحی')),
                ('surgeon_name', models.CharField(max_length=100, verbose_name='نام جراح')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgical_procedures', to='treatment.upperbodyliftpatient', verbose_name='بیمار')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UpperBodyLiftPreTreatmentAssessment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('weight', models.FloatField(verbose_name='وزن بیمار (کیلوگرم)')),
                ('height', models.FloatField(verbose_name='قد بیمار (متر)')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_treatment_assessments', to='treatment.upperbodyliftpatient', verbose_name='بیمار')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UpperBodyLiftPostTreatmentFollowUp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('visit_date', models.DateField(verbose_name='تاریخ ویزیت پس از درمان')),
                ('follow_up_notes', models.TextField(verbose_name='یادداشت\u200cهای پیگیری')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_treatment_follow_ups', to='treatment.upperbodyliftpatient', verbose_name='بیمار')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
