# Generated by Django 4.2.3 on 2023-08-28 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0053_upperbodyliftpatient_upperbodyliftsurgicalprocedure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrachioplastyPatient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrachioplastyProcedure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='treatment.brachioplastypatient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrachioplastyDuringTreatment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('procedure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='during_treatment', to='treatment.brachioplastyprocedure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrachioplastyBeforeTreatment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('procedure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='before_treatment', to='treatment.brachioplastyprocedure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrachioplastyAfterTreatment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('procedure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='after_treatment', to='treatment.brachioplastyprocedure')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
