# Generated by Django 4.2.3 on 2023-08-28 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0054_brachioplastypatient_brachioplastyprocedure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tummyTuck_Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('birth_date', models.DateField(verbose_name='تاریخ تولد')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='tummyTuck_Treatment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('treatment_date', models.DateField(verbose_name='تاریخ درمان')),
                ('description', models.TextField(verbose_name='توضیحات درمان')),
                ('before_photos', models.ImageField(upload_to='tummyTuck/before/', verbose_name='تصاویر پیش از درمان')),
                ('after_photos', models.ImageField(upload_to='tummyTuck/after/', verbose_name='تصاویر بعد از درمان')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.tummytuck_patient', verbose_name='بیمار')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
