# Generated by Django 4.2.3 on 2023-08-28 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_remove_user_group_delete_groupsuser'),
        ('treatment', '0055_tummytuck_patient_tummytuck_treatment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiposuctionPatient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liposuction_patients', to='common.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiposuctionPrescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('medication', models.CharField(max_length=100, verbose_name='نام دارو')),
                ('dosage', models.CharField(max_length=50, verbose_name='مقدار دوز دارو')),
                ('usage_instructions', models.TextField(verbose_name='دستورات مصرف دارو')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiposuctionTreatment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('visit_date', models.DateTimeField(verbose_name='تاریخ ویزیت')),
                ('symptoms', models.TextField(verbose_name='علائم بیماری')),
                ('diagnosis', models.TextField(verbose_name='تشخیص بیماری')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.liposuctionpatient', verbose_name='بیمار')),
                ('prescriptions', models.ManyToManyField(blank=True, to='treatment.liposuctionprescription', verbose_name='نسخه\u200cهای دارویی')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiposuctionProcedure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('procedure_date', models.DateTimeField(verbose_name='تاریخ عمل')),
                ('preoperative_assessment', models.TextField(verbose_name='ارزیابی پیش از عمل')),
                ('intraoperative_details', models.TextField(verbose_name='جزئیات داخل عمل')),
                ('postoperative_instructions', models.TextField(verbose_name='دستورات پس از عمل')),
                ('complications', models.TextField(blank=True, verbose_name='مشکلات و عوارض')),
                ('follow_up_notes', models.TextField(blank=True, verbose_name='یادداشت\u200cهای پیگیری')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.liposuctionpatient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'روش درمانی Liposuction',
                'db_table': 'liposuction_procedure',
            },
        ),
        migrations.CreateModel(
            name='LiposuctionPreoperativeAssessment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('assessment_details', models.TextField(verbose_name='جزئیات ارزیابی پیش\u200cعملیاتی')),
                ('treatment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preoperative_assessment', to='treatment.liposuctiontreatment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiposuctionPostoperativeDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('recovery_instructions', models.TextField(verbose_name='دستورات بازیابی')),
                ('complications', models.TextField(verbose_name='مشکلات پس از جراحی')),
                ('treatment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postoperative_details', to='treatment.liposuctiontreatment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiposuctionPostOperativeCare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('postoperative_instructions', models.TextField(verbose_name='دستورات پس از عمل جراحی')),
                ('treatment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='treatment.liposuctiontreatment', verbose_name='روند درمانی')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiposuctionIntraoperativeDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('procedure_details', models.TextField(verbose_name='جزئیات عمل جراحی')),
                ('anesthesia_type', models.CharField(max_length=100, verbose_name='نوع بیهوشی')),
                ('treatment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intraoperative_details', to='treatment.liposuctiontreatment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
