# Generated by Django 4.2.3 on 2023-08-28 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_remove_user_group_delete_groupsuser'),
        ('treatment', '0056_liposuctionpatient_liposuctionprescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liposuctionprocedure',
            name='surgeon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='common.person', verbose_name='جراح'),
        ),
    ]
