# Generated by Django 4.2.3 on 2023-08-28 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0057_liposuctionprocedure_surgeon'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoolSculptingPatient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('full_name', models.CharField(max_length=100, verbose_name='نام کامل بیمار')),
                ('age', models.PositiveIntegerField(verbose_name='سن بیمار')),
            ],
            options={
                'db_table': 'CoolSculptingPatient',
            },
        ),
        migrations.CreateModel(
            name='CoolSculptingTreatment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('treatment_date', models.DateTimeField(verbose_name='تاریخ درمان')),
                ('treatment_area', models.CharField(max_length=100, verbose_name='ناحیه درمانی')),
                ('session_number', models.PositiveIntegerField(verbose_name='تعداد جلسات درمان')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.coolsculptingpatient', verbose_name='بیمار')),
            ],
            options={
                'db_table': 'CoolSculptingTreatment',
            },
        ),
        migrations.CreateModel(
            name='CoolSculptingPrescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('medication', models.CharField(max_length=100, verbose_name='نام دارو')),
                ('dosage', models.CharField(max_length=50, verbose_name='مقدار دوز دارو')),
                ('usage_instructions', models.TextField(verbose_name='دستورات مصرف دارو')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.coolsculptingtreatment', verbose_name='روند درمانی')),
            ],
            options={
                'db_table': 'CoolSculptingPrescription',
            },
        ),
    ]
