# Generated by Django 4.2.3 on 2023-09-02 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nursing', '0001_initial'),
        ('common', '0021_remove_user_group_delete_groupsuser'),
        ('administration', '0003_company_description_company_document_company_name'),
        ('treatment', '0062_alter_specialty_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.person'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='nurse',
            field=models.ManyToManyField(related_name='procedure_company', to='nursing.nurses'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='physician',
            field=models.ManyToManyField(related_name='procedure_company', to='treatment.physician'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='treatment.qualification'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='skills',
            field=models.TextField(null=True, verbose_name='مهارت\u200cها'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedure', to='administration.company'),
        ),
    ]
