# Generated by Django 4.2.3 on 2023-09-03 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0063_procedure_head_procedure_nurse_procedure_physician_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='company',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='head',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='nurse',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='physician',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='subspecialty',
            name='company',
        ),
        migrations.RemoveField(
            model_name='subspecialty',
            name='head',
        ),
        migrations.RemoveField(
            model_name='subspecialty',
            name='nurse',
        ),
        migrations.RemoveField(
            model_name='subspecialty',
            name='physician',
        ),
        migrations.RemoveField(
            model_name='subspecialty',
            name='qualification',
        ),
    ]
