# Generated by Django 4.2.3 on 2023-09-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0064_remove_specialty_company_remove_specialty_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physician',
            name='specialties',
            field=models.ManyToManyField(through='treatment.PhysicianSpecialty', to='treatment.specialty'),
        ),
        migrations.AddField(
            model_name='physician',
            name='subspecialty',
            field=models.ManyToManyField(blank=True, related_name='physicain', to='treatment.subspecialty'),
        ),
    ]
