# Generated by Django 4.2.3 on 2023-09-03 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nursing', '0001_initial'),
        ('treatment', '0065_physician_specialties_physician_subspecialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='prep_nurse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nursing.nurses'),
        ),
    ]
