# Generated by Django 4.2.3 on 2023-09-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0066_appointment_prep_nurse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='company',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='head',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='nurse',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='physician',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='qualification',
        ),
        migrations.AddField(
            model_name='procedure',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
