# Generated by Django 4.2.3 on 2023-09-03 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0067_remove_procedure_company_remove_procedure_head_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicianProcedure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.physician')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.procedure')),
                ('qualification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physician_procedure', to='treatment.qualification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='physician',
            name='procedure',
            field=models.ManyToManyField(related_name='Physician', through='treatment.PhysicianProcedure', to='treatment.procedure'),
        ),
    ]
