# Generated by Django 4.2.3 on 2023-09-03 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_remove_user_group_delete_groupsuser'),
        ('treatment', '0068_physicianprocedure_physician_procedure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellrepresentation',
            options={'verbose_name': 'نماینده\u200cی فروش', 'verbose_name_plural': 'نمایندگان فروش'},
        ),
        migrations.RemoveField(
            model_name='sellrepresentation',
            name='document',
        ),
        migrations.AlterField(
            model_name='sellrepresentation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_representation', to='common.person'),
        ),
        migrations.RemoveField(
            model_name='sellrepresentation',
            name='specialties',
        ),
        migrations.AddField(
            model_name='sellrepresentation',
            name='specialties',
            field=models.ManyToManyField(related_name='sell_representation', to='treatment.specialty'),
        ),
    ]
