# Generated by Django 4.2.3 on 2023-09-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0069_alter_sellrepresentation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='abbreviation',
            field=models.CharField(max_length=50, verbose_name='مخفف تخصص'),
        ),
    ]
