# Generated by Django 4.2.3 on 2023-09-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0070_alter_specialty_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='description',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
    ]
