# Generated by Django 4.2.3 on 2023-09-06 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financialhub', '0003_alter_cost_classification'),
        ('treatment', '0072_alter_procedure_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='cost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_procedure', to='financialhub.cost', verbose_name='هزینه (در واحد پولی)'),
        ),
    ]
