# Generated by Django 4.2.3 on 2023-09-06 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_company_description_company_document_company_name'),
        ('nursing', '0001_initial'),
        ('common', '0027_alter_educationaldegree_abbreviation'),
        ('treatment', '0073_alter_procedure_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedure', to='administration.company'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.person'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='nurse',
            field=models.ManyToManyField(related_name='procedure_company', to='nursing.nurses'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='physician',
            field=models.ManyToManyField(related_name='procedure_company', to='treatment.physician'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='treatment.qualification'),
        ),
    ]
