# Generated by Django 4.2.5 on 2023-09-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0074_procedure_company_procedure_head_procedure_nurse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalplan',
            name='deleted_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='medicalplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalplan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
