# Generated by Django 4.2.5 on 2024-01-04 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurses',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('position', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=100)),
                ('registered', models.BooleanField()),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.person')),
            ],
            options={
                'verbose_name': 'Nurse',
                'verbose_name_plural': 'Nurses',
            },
        ),
        migrations.CreateModel(
            name='NursingService',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('service_type', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nursing.nurses')),
            ],
            options={
                'verbose_name': 'Nursing Service',
                'verbose_name_plural': 'Nursing Services',
            },
        ),
        migrations.CreateModel(
            name='NursesSpecialty',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_specialty', to='nursing.nurses')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NursesMedicalCenter',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('credentials', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.document')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursing.nurses')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
