# Generated by Django 4.2.5 on 2023-12-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing', '0003_alter_nurses_id_alter_nursesmedicalcenter_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurses',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nursesmedicalcenter',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nursesspecialty',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nursingservice',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
